### ISSUE TITLE
Interupt with "userDetection" while "goToLocation"

### ISSUE THREAD

**Issue by vicnando** [robotemi/sdk#103]
Hi , i have a problem with user detection. In my case i need to make my temi to patrol and detect people nearby and say greetings. But when i use robot.goTo("location") . The detection Listener is not trigger at all.

Is that because if temi focus on go to location , all listener will be delayed until Temi arrive to somewhere location ?

Please help me, Thanks!

**Comment by lcgao** [comment]
Yes, that's correct, detection mode will stop when temi focus on go to location.

**Comment by vicnando** [comment]
Btw. Can we make the detection more wider and far.  Is there any idea for
that? Thx for your response

**Comment by lcgao** [comment]
Developers can extend the detection distance in next offical version.

**Comment by vicnando** [comment]
So, can i know when the the next version will be release then?

**Comment by lcgao** [comment]
It's still in testing, and updates will be pushed when it is officially released.
