### ISSUE TITLE
I want Temi Assistant to support Vietnamese. Can I implement it?

### ISSUE THREAD

**Issue by lecong** [robotemi/sdk#109]
Hi Team,

I want implement for Temi Assistant support Vietnamese. How to implement it?

Thanks,

**Comment by zjn0505** [comment]
In the coming release of temi SDK and software update, there are options to intercept wakeup.
Thus you will be able to do your own voice recognition, and NLP.

**Comment by lecong** [comment]
have plan for this feature?

**Comment by zjn0505** [comment]
The SDK support of intercepting voice flow has already been released.

Take sample app for example, as a Kiosk app, once it declares the following meta data in the manifest, it will be able to take over the voice flow, handing with its own STT and NLU engine.
```
<meta-data
            android:name="@string/metadata_override_nlu"
            android:value="true" />

<meta-data
           android:name="@string/metadata_override_stt"
           android:value="true" />
```

The SDK documentation is getting updated for this and the rest major changes of this version, and the robot software will be available in the next OTA update.

**Comment by s2nmt** [comment]
Do you have a solution for this yet? Can you show me?
