### ISSUE TITLE
how to change Temi Screensaver with custom screen 

### ISSUE THREAD

**Issue by Sandeepkrjain** [robotemi/sdk#112]
Need to have custom screensaver on Temi for corporate messaging ?

**Comment by lcgao** [comment]
Hello, please consider using the [Kiosk mode](https://github.com/robotemi/sdk/wiki/Kiosk-Mode).

**Comment by manhaha** [comment]
Hi @lcgao , after I turned on the Kiosk mode and select my app, Temi still display a black screen and time clock after a period of time. Is it normal?

Can i turn the time clock screensaver off in kiosk mode and let the kiosk app always on? Thanks a lot.

**Comment by lcgao** [comment]
Sure, go to *Settings > General > Stand by* to turn off the screensaver.

**Comment by manhaha** [comment]
Thx @lcgao , you are life saver.

May I ask one more temi kiosk app question, which is how to hide the Android navigation bar?? I set my app as kiosk app, and I tried to call the following code in MainActivity OnCreate/OnResume/OnStart, but no luck. Can you give me a little hint?

`    public void FullScreencall() {
        if(Build.VERSION.SDK_INT < 19){
            View v = this.getWindow().getDecorView();
            v.setSystemUiVisibility(View.GONE);
        } else {
            //for higher api versions.
            View decorView = getWindow().getDecorView();
            int uiOptions = View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;
            decorView.setSystemUiVisibility(uiOptions);
        }
    }`

**Comment by lcgao** [comment]
Do you mean the navigation bar on the top of screen? If so, there are two solution to solve it:
- Swipe up in the top bar directly.
-  Use `Robot.getInstance().hideTopBar()` to hide it programmatically.

Hope this help.

**Comment by manhaha** [comment]
Hi @lcgao 

No,  I mean the native android navigation bar, with back, home and rectangle button like:

![DSC_0221](https://user-images.githubusercontent.com/68810961/91651118-25ab7900-eabb-11ea-8e30-2fb06cd81e85.JPG)


My kiosk app had the top bar hidden as you suggested, but a floating half transparent android navigation bar always be there. Any way to hide it?

**Comment by lcgao** [comment]
I think this is a external Navigation bar App that installed by user, so just `force-stop` this App to remove the floating navigation bar.

**Comment by manhaha** [comment]
Hi @lcgao ,

Oh I see, thanks a lot! It truely is.
