### ISSUE TITLE
How to make the app run all the time ?

### ISSUE THREAD

**Issue by Sandeepkrjain** [robotemi/sdk#113]
I need my app to run all the time on Temi. The user should be able to interact anytime. The App crashes or stops as after couple of mins. The system starts the screensaver which we do not want and get ride completely.

**Comment by lcgao** [comment]
Hello, please consider using the [Kiosk mode](https://github.com/robotemi/sdk/wiki/Kiosk-Mode).

**Comment by saboutal** [comment]
Hi, is there a possibility to let temi listen all the time, not with wakeupword od askquestion().
Thanks
