### ISSUE TITLE
how to make temi say customer sentence / words instead of just "Hello"  in Greeter mode

### ISSUE THREAD

**Issue by Sandeepkrjain** [robotemi/sdk#114]
how to make temi say customer sentence / words instead of just "Hello" in Greeter mode

**Comment by lcgao** [comment]
Unfortunately currently this part does not support customization, but you can choose to hide it via method [`Robot.getInstance().setTopBadgeEnabled(false)`](https://github.com/robotemi/sdk/wiki/Utils#setTopBadgeEnabled).
