### ISSUE TITLE
ToggleNavigationBillboard not working

### ISSUE THREAD

**Issue by jesusonoro** [robotemi/sdk#115]
Function robot.toggleNavigationBillboard(true); doesn't disable the navigation billboard.
This doesn't works on the sample-sdk. Is there something else to do for the method to work?

**Comment by lcgao** [comment]
Hello, please let me know the versions of your Launcher OS  & SDK. If you use the latest temi SDK(0.10.70) & Launcher(13582+), you need [request the Settings permission](https://github.com/robotemi/sdk/wiki/permission#requestPermissions) and set your App as the Kiosk App first. And if your Launcher is not the latest, please use the old version temi SDK (0.10.65) instead.

**Comment by jesusonoro** [comment]
Hi, my Temi's Launcher OS is 13377 and I'm using the latest SDK, i will try using the old version temi sdk then. Thank you!

**Comment by jesusonoro** [comment]
Using the old version temi SDK solved the problem. Thanks!
