### ISSUE TITLE
Disabling detection mode with setDetectionModeOn

### ISSUE THREAD

**Issue by dporfirio** [robotemi/sdk#119]
Hello,

I am trying to use the setDetectionModeOn() functionality to programatically turn on/off human detection. If Track User is enabled in the settings (previously welcome mode?) I cannot disable detection mode with setDetectionModeOn(false). I still receive calls to the detection state changed callback, and Temi continues to track my movement.

On the other hand, if I disable Track User, I seemingly cannot re-enable it with setDetectionModeOn(true). No callbacks are received, and Temi's IR camera looks like it's turned off.

My app is in Kiosk mode. Is there something I'm missing?

**Comment by lcgao** [comment]
Hello, detection mode is one of the system settings, so the Settings permission is required for this method. So please request the Settings permission before using it if your App still does not have the related permission.

How to request permission: https://github.com/robotemi/sdk/wiki/permission#request-skill-permissions.
