### ISSUE TITLE
Get Temi's current Position

### ISSUE THREAD

**Issue by bruno963852** [robotemi/sdk#120]
On the updated documentation there's a new function to make Temi go to a location passing a Position object with the coordinates and yaw, and tiltAngle. Then:

1. Whats the "yaw" parameter?
2. Apparently there's no way to get Temi's current Position object (coordinates and stuff...), or am i wrong?

**Comment by lcgao** [comment]
1. Yaw angle relative to Home base.

2. Current position is easy to change so please use [OnCurrentPositionChangedListener](https://github.com/robotemi/sdk/wiki/Locations#onCurrentPositionChangedListener) to get the current position.
