### ISSUE TITLE
安裝SDK後app停止運作

### ISSUE THREAD

**Issue by Fongliang** [robotemi/sdk#121]
您好，我將將sdk-0.10.70.aar import後 app會停止運作如下圖
![81971](https://user-images.githubusercontent.com/42931993/93184890-5d7b1780-f76f-11ea-905d-7746fbac2264.jpg)
想請問可能會是發生什麼問題，是因為我這邊的temi是中國版的嗎?或是code有問題，想請問有提供使用sdk的sample code嗎?

**Comment by Fongliang** [comment]
附上我用來測試SDK是否順利import的測試用code

![image](https://user-images.githubusercontent.com/42931993/93429054-1ae24800-f8f3-11ea-8fca-3f120cb73156.png)

**Comment by lcgao** [comment]
你好，麻烦提供一下崩溃（crash）日志，以及temi版本号（设置>关于）。

**Comment by Fongliang** [comment]
![image](https://user-images.githubusercontent.com/42931993/93429594-faff5400-f8f3-11ea-841d-bafa1c3ddf7b.png)
![image](https://user-images.githubusercontent.com/42931993/93429610-ffc40800-f8f3-11ea-8c89-e675761b47c0.png)

**Comment by lcgao** [comment]
你好，这个temi的版本比较旧了，无法使用最新版本的SDK。目前解决方法有：

1. 联系我们的技术支持或者分销商进行版本升级。
2. 继续使用旧版本机器，同时使用旧版本SDK：`implementation 'com.robotemi:sdk-china:0.10.49'`。

推荐升级到最新版本。

**Comment by Fongliang** [comment]
![image](https://user-images.githubusercontent.com/42931993/93430801-cab8b500-f8f5-11ea-8d01-23f78b2256f1.png)
我後來有改用sdk-china-0.10.49.aar也是不行

**Comment by lcgao** [comment]
改成0.10.49出现的崩溃的日志麻烦也提供一下

**Comment by Fongliang** [comment]
![image](https://user-images.githubusercontent.com/42931993/93431174-57637300-f8f6-11ea-8c6e-05bac184ff0c.png)

**Comment by lcgao** [comment]
这个.aar是自己手动编译的吧？通过 `implementation 'com.robotemi:sdk-china:0.10.49'` 集成吧。

**Comment by Fongliang** [comment]
是把aar放在libs中然後再下圖dependencies區域加入implementation 'com.robotemi:sdk-china:0.10.49'嗎?
![image](https://user-images.githubusercontent.com/42931993/93431848-49622200-f8f7-11ea-996a-023d370f3abf.png)

**Comment by lcgao** [comment]
是的

**Comment by Fongliang** [comment]
好的感謝您的幫忙我再試試看

**Comment by Fongliang** [comment]
> 你好，这个temi的版本比较旧了，无法使用最新版本的SDK。目前解决方法有：
> 
> 1. 联系我们的技术支持或者分销商进行版本升级。
> 2. 继续使用旧版本机器，同时使用旧版本SDK：`implementation 'com.robotemi:sdk-china:0.10.49'`。
> 
> 推荐升级到最新版本。

請問如果要進行版本更新一定要經過分销商嗎?

**Comment by lcgao** [comment]
或者通过这里：https://www.robotemi.com/helpdesk/  来联系我们的技术支持。

**Comment by Fongliang** [comment]
> 或者通过这里：https://www.robotemi.com/helpdesk/ 来联系我们的技术支持。

如果經由這個方式的話可以不將機器人送回，自行將temi進行版本更新嗎?
是透過下圖的地方進行聯繫嗎?請問有中文的技術支持嗎?
感謝您的幫忙!
![image](https://user-images.githubusercontent.com/42931993/93557823-8e955b00-f9ae-11ea-86f7-e64fda518b37.png)

**Comment by lcgao** [comment]
不需要寄回机器人，会有中文技术支持安排推送更新的。

**Comment by Fongliang** [comment]
> 不需要寄回机器人，会有中文技术支持安排推送更新的。

適用下圖的地方申請支持嗎?
![image](https://user-images.githubusercontent.com/42931993/93558377-e84a5500-f9af-11ea-87a7-9b7d75255b77.png)

**Comment by lcgao** [comment]
https://robotemi.zendesk.com
在这里注册账号提交工单吧

**Comment by Fongliang** [comment]
好的感謝您!
