### ISSUE TITLE
skidJoy API does not control move smoothly

### ISSUE THREAD

**Issue by Jeff-Zhu** [robotemi/sdk#126]
I am trying to use the skidJoy to Temi turning radius, but regardless what other values I used, it always seems to be treated as 0, or 1. 
Such as skidJoy(0.5, 0) behaves as same as skidJoy(1,0). 
And skidJoy(0.5, 1) is same as skidJoy(1,1).
And skidJoy(0.25, 1) is actually only turning.

BTW, I do have to repeat the skdJoy every 500ms, otherwise Temi won't move.

Is it possible to change turning radius on the move continuously?

**Comment by lcgao** [comment]
Please consider using [`Robot.getInstance().turnBy(int degrees)`](https://github.com/robotemi/sdk/wiki/Movement#turnBy).

**Comment by zjn0505** [comment]
> BTW, I do have to repeat the skdJoy every 500ms, otherwise Temi won't move.

This is expected.

**Comment by root221** [comment]
What is the difference between skidjoy(0.5,0) and skidjoy(1,0)

**Comment by lcgao** [comment]
Using `skidJoy(0.5, 0)` will move forward temi with 0.5 * max speed. `skidJoy(1, 0)` will move with the max speed.
