### ISSUE TITLE
wait for turnBy to be finished

### ISSUE THREAD

**Issue by Synizter** [robotemi/sdk#128]
I have create a program that make step of movement (eg. forward, left, right and backward) my problem is that when I use _**turnBy**_ command, The program does not wait a _**turnBy**_ command before executing another command (for forward and backward, I use skidjoy) 

Is is possible to check if robot is done turning by from **_turnBy_** command?

**Comment by lcgao** [comment]
Sorry, there is no way to check if the turnBy task is done for now.
