### ISSUE TITLE
Which is the cause of TtsListener Status NOT_ALLOWED

### ISSUE THREAD

**Issue by ookuma** [robotemi/sdk#129]
I am testing the speak function using TtsRequest, but sometimes Temi does not speak and throws an error. 
At this time, TtsListener has notified Status: NOT_ALLOWED.
I want to find out the reason of this error.

The reference(https://github.com/robotemi/sdk/wiki/Speech#ttsRequest) says "Play is not allowed".
Specifically, under what circumstances and settings is playback prohibited?

**Comment by lcgao** [comment]
TTS would not be allowed when temi is doing ASR.
