### ISSUE TITLE
Hide Temi Top Bar from Application

### ISSUE THREAD

**Issue by NumanGillani-jackys** [robotemi/sdk#131]
Hello, I am trying to hide the Temi Top Bar of Time/Battery/Settings etc from my Application. How can I do it programmatically?

**Comment by NumanGillani-jackys** [comment]
> Hello, I am trying to hide the Temi Top Bar of Time/Battery/Settings etc from my Application. How can I do it programmatically?

I found the answer by myself.

**Comment by Vorlif** [comment]
Have you seen issue #89 ?

**Comment by NumanGillani-jackys** [comment]
> Have you seen issue #89 ?

Yeah, Thanks for the link, that's what I was looking for.
