### ISSUE TITLE
機器人移動中語音警示listener

### ISSUE THREAD

**Issue by Fongliang** [robotemi/sdk#133]
我想要在機器人移動中時發出語音警示ex:"機器人移動中，請小心"
但是onDistanceToLocationChanged和onCurrentPositionChanged 這兩個Listener觸發的頻率太快，無法唸完一句話就再次觸發
onGoToLocationStatusChanged這個Listener如果沒有遇到status改變的話可能一次點到點的移動過程中只會觸發一次警示
想請問有適合這個例子的Listener嗎?

**Comment by zjn0505** [comment]
目前没有适合这个场景直接可用的 listener

对于 地点 -> 地点的移动 可以考虑两个 listener 的组合。
通过`onGoToLocationStatusChangedListner`决定是否为点到点的移动过程。
当坐标变化时，`onCurrentPositionChanged` 和 `onDistanceToLocationChanged` 会同时触发，选择其中一个即可。
配合类似于 [throttleFirst](http://reactivex.io/documentation/operators/sample.html) 的操作，只响应一段时间内的首个坐标更新事件。

**Comment by Fongliang** [comment]
OK
