### ISSUE TITLE
Application icon not showing on Temi Screen

### ISSUE THREAD

**Issue by NumanGillani-jackys** [robotemi/sdk#136]
Whenever I install the Application on Temi, it works absolutely fine. There is no issues, but when I close the application, I found there is no App icon of my Application. So I've to again connect Temi, and install from my Android Studio.

Is there anything wrong I am doing? Do I've to put any extra code in my project to show App icon?

**Comment by lcgao** [comment]
Add following code as a child of the `<application>` element to AndroidManifest.xml.

``` xml
<meta-data
        android:name="com.robotemi.sdk.metadata.SKILL"
        android:value="@string/app_name" />
```
[Example](https://github.com/robotemi/sdk/blob/master/sample/src/main/AndroidManifest.xml#L19-L21)
