### ISSUE TITLE
Install and debug of applications on Temi

### ISSUE THREAD

**Issue by mmorisco** [robotemi/sdk#139]
Hi, I am developing an application for Temi. Every time I need to debug my application on Temi I see that it's really slow the installation through the wireless ADB... is there any faster other option for installing an application to Temi instead the wireless ADB, like adb install through usb cable? I spent 15 minutes every installation and, you know, it's really long time for debug purpose...

**Comment by YoungHoi-Heo** [comment]
I have the same problem. wireless debug is too slow.

**Comment by lcgao** [comment]
Unfortunately the wireless ADB is the only way to install application to temi for now.
