### ISSUE TITLE
Potential issue in sample project gradle file

### ISSUE THREAD

**Issue by defjam903** [robotemi/sdk#14]
the application immediately gets the following error

Could not find method android() for arguments [build_8swd2bg3abnivrlw4mwkaa61z$_run_closure1@591a308a] on root project 'SAMPLE' of type org.gradle.api.Project.
Open File

**Comment by ramisaban1** [comment]
Can you please explain the process you took that led up to this error?

**Comment by defjam903** [comment]
The issue that accrued was a straight download of the sample application that you all have posted that caused an error immediately after compiling. I tried to dig a bit into what could be causing the compiler failure but it may have something to do with the SDK.
