### ISSUE TITLE
OnTelepresenceStatusChangedListener 無法使用 

### ISSUE THREAD

**Issue by Fongliang** [robotemi/sdk#140]
您好，
我在新增OnTelepresenceStatusChangedListener會出現下列錯誤，，顯示 interface expected here
![image](https://user-images.githubusercontent.com/42931993/99227347-0ef90080-2826-11eb-940c-515e75ab44dc.png)

**Comment by lcgao** [comment]
您好，就如错误提示所说，`implements` 后面接的应该是 `interface` (接口)，但是 `OnTelepresenceStatusChangedListener` 是个 `class` (类)，不能接在 `implements` 后面。

**Comment by Fongliang** [comment]
請問如果不是interface我要怎麼宣告OnTelepresenceStatusChangedListener?以及如何讓OnTelepresenceStatusChangedListener監聽
TelepresenceStatus，直接Robot.getInstance().addOnTelepresenceStatusChangedListener();嗎?

**Comment by lcgao** [comment]
如果满足需求的话，建议使用 [`interface OnTelepresenceEventChangedListener {}`](https://github.com/robotemi/sdk/wiki/Users-&-Telepresence_chn#addOnTelepresenceEventChangedListener)，这样就可以和其他监听器接口一样使用了。

**Comment by Fongliang** [comment]
好的感謝您!
