### ISSUE TITLE
Screen Recording

### ISSUE THREAD

**Issue by SebastianLiando** [robotemi/sdk#143]
Hi, is there a way to record temi's screen for better documentation purpose?

Android Studio's screen record feature stops immediately after starting. Also tried with scrcpy, but an exception is thrown. Mobizen app can not even run in temi.

**Comment by lcgao** [comment]
Hi, we will release new version for Android OS firmware to solving this kind of issue in the future.

**Comment by zjn0505** [comment]
> Hi, is there a way to record temi's screen for better documentation purpose?
> 
> Android Studio's screen record feature stops immediately after starting. Also tried with scrcpy, but an exception is thrown. Mobizen app can not even run in temi.

Can you check what will happen if using
> scrcpy -m 1024

**Comment by SebastianLiando** [comment]
> > Hi, is there a way to record temi's screen for better documentation purpose?
> > Android Studio's screen record feature stops immediately after starting. Also tried with scrcpy, but an exception is thrown. Mobizen app can not even run in temi.
> 
> Can you check what will happen if using
> 
> > scrcpy -m 1024

Hi, thanks for the suggestion.

Yup, it is now able to cast temi's screen. However, it seems like the tool can not manage the orientation properly. As attached, the screen is cast vertically, but the controls work horizontally (swiping left and right works although the screen is vertical). 

<img width="701" alt="example" src="https://user-images.githubusercontent.com/60729951/101735715-3aa59880-3afd-11eb-836a-1e6f968c8334.png">

**Comment by zjn0505** [comment]
Thanks for the info. temi's next Android firmware OTA will fix this rotation issue.
We will rollout this OTA gradually.

Please contact temi customer support and provide the robot serial number.
It can be found on the robot under `Settings -> About -> Serial Number`.

**Comment by zjn0505** [comment]
OTA firmware ver. 20201216 is rolling out to fix this issue.

**Comment by Thiago-LM** [comment]
I can confirm that `scrcpy -m 1024` works now on latest firmware.

![Captura de Tela 2021-05-27 às 11 07 20](https://user-images.githubusercontent.com/37124257/119841332-16d3e480-bedc-11eb-8014-ad906e073d5c.png)
