### ISSUE TITLE
Overriding the onRobotReady method

### ISSUE THREAD

**Issue by LeoFau** [robotemi/sdk#145]
Hello I am pretty new to programming in general and trying to create an app on the temi robot in course of writing an essay for college.

I tried to follow the instructions on starting as explained in the wiki. When I paste in the paragraph on overriding the onRobotReady method, Android Studio does not recognize the "robot"-parameter? What do I need to do, to change this?
![image](https://user-images.githubusercontent.com/75070832/100337760-16fc3180-2fd8-11eb-9d6f-c8c031ceb424.png)

Thank you in advance!

Leo

**Comment by lcgao** [comment]
Hello, please replace `robot.onStart(activityInfo)` to `Robot.getInstance().onStart(activityInfo)`.

**Comment by LeoFau** [comment]
Thank you, that worked!
