### ISSUE TITLE
Which Tablet is Temi using 

### ISSUE THREAD

**Issue by arpit999** [robotemi/sdk#148]
I would like to design my app in emulator so I need the hardware configuration for Android Emulator. Could you provide Tablet name and model number?

**Comment by Thiago-LM** [comment]
At their website they have some specifications regarding temi's hardware: [specs](https://www.robotemi.com/specs/).

But if you are wondering about the real hardware behind temi's android tablet, as per information given by adb, it seems to be an rk3288 ([Wikipedia](https://en.wikipedia.org/wiki/Rockchip_RK3288) and [Rockchip Wiki](http://opensource.rock-chips.com/wiki_RK3288)), which may indicate some embedded board running Android.
