### ISSUE TITLE
How to set the image in app 

### ISSUE THREAD

**Issue by arpit-temi** [robotemi/sdk#149]
I added image in app icon but it is too small I would like to set an image on the grey rectangle. Is possible? if it is then where do I specify the image.

 
![device-2020-12-15-151131](https://user-images.githubusercontent.com/76004838/102267426-e0834980-3ee7-11eb-8e85-9a80faacf3b8.png)

**Comment by lcgao** [comment]
Please try to change your application icon resource to a larger resolution.

**Comment by lcgao** [comment]
Ask UI Designer for the larger image that as the App icon.
