### ISSUE TITLE
When sending Temi to a location programmatically, does she still abide by the rules set in the Temi Center?

### ISSUE THREAD

**Issue by Daisykh** [robotemi/sdk#157]
Hi, I was wondering if Temi will respect the virtual walls and paths (from the Temi Center) when sent to a location via the `goTo()` method?

**Comment by lcgao** [comment]
Sure, you should be able to see the virtual walls and paths in the Map editor right? So any way(like `goTo()` or voice command) to trigger the navigation should respect the rules.
