### ISSUE TITLE
How to catch the temis' nickname?

### ISSUE THREAD

**Issue by Rogerlee5566** [robotemi/sdk#158]
How to read temi’s nickname, not serial number.

![WeChat 圖片_20210107182200](https://user-images.githubusercontent.com/59472520/103881485-77bd7480-5115-11eb-87e4-b308b1e32699.jpg)

**Comment by lcgao** [comment]
There is no related function to get nickname in current temi SDK.

**Comment by lcgao** [comment]
Getting temi's nickname is available from [version 0.10.77](https://github.com/robotemi/sdk/wiki/Utils#getNickName).
