### ISSUE TITLE
Temi Robot的人臉辨識功能無法運作

### ISSUE THREAD

**Issue by YoYoJohn** [robotemi/sdk#159]
您好，我目前有在使用Temi上面的人臉辨識，以下是我執行的畫面。
![440634](https://user-images.githubusercontent.com/32160677/104001428-9afe2780-51da-11eb-8275-3bb1aee2d3ff.jpg)
當我按下左上角Button的時候，會觸發startFaceRecognition()這個function，但是他完全沒有反應。

我已經有事先確認已經把商店模式開啟了，人臉辨識權限也有開啟了，但還是沒有反應。
![440633](https://user-images.githubusercontent.com/32160677/104001601-dac50f00-51da-11eb-8007-d852f8f8ecf1.jpg)
![440632](https://user-images.githubusercontent.com/32160677/104001608-de589600-51da-11eb-87d2-cc47671c61dc.jpg)

**Comment by lcgao** [comment]
你好，请确保已经在temi Center（temi 管理平台）中预先配置好了联系人人脸信息并分配到了这台 temi 上。
