### ISSUE TITLE
Can I change the temi's voice with the code?

### ISSUE THREAD

**Issue by Sunjuhyeong** [robotemi/sdk#161]
Hello!

Can I change the temi's voice with the code, not by saying “hey temi, change your voice”?

**Comment by lcgao** [comment]
Hello, currently there is no related function to change temi's voice via temi SDK.

**Comment by jesusonoro** [comment]
You can try playing audios as response to interactions

**Comment by zjn0505** [comment]
You can consider this function. https://github.com/robotemi/sdk/wiki/Speech#startDefaultNlu
`startDefaultNlu("Change your voice")`
