### ISSUE TITLE
How to upload picture to temi for realtime face recognition?

### ISSUE THREAD

**Issue by Rogerlee5566** [robotemi/sdk#165]
您好, 
請問, 
1. 如何上載照片到temi做即時人臉辨識應用?
2. 或是目前的temi人臉辨識, 只能配合temi center 上傳照片到temi?
3. temi人臉辨識的辨識engine是在temi center端嗎?
4. 上載的照片是Located在China? or USA?

Thank you~

**Comment by lcgao** [comment]
您好，目前只能通过配合 temi Center 上传照片来进行人脸识别；temi 的人脸识别 engine 部署在 temi 机器人端；
