### ISSUE TITLE
請問tts可以判斷語言或指定語言發音嗎?

### ISSUE THREAD

**Issue by Fongliang** [robotemi/sdk#168]
我使用tts輸入的是印尼語，但因為印尼語也是英文字母，所以tts會用英文的發音來說，而不是印尼語的發音。
所以想請問tts api可以指定語言發音嗎?

**Comment by lcgao** [comment]
目前不可以的。

**Comment by Fongliang** [comment]
好的，那請問這方面有辦法可以解決嗎?

**Comment by lcgao** [comment]
不能实时指定语言，只有在系统语言是印尼语时播报的TTS才会是印尼语。

**Comment by Fongliang** [comment]
好的了解感謝
