### ISSUE TITLE
Can I subscribe to volume changes?

### ISSUE THREAD

**Issue by sokolyaka** [robotemi/sdk#169]
We have getVolume(); method, but if the volume changed manually, have we the ability to subscribe to the event?

**Comment by lcgao** [comment]
Currently no, but you can try to subscribe the system broadcast from Android OS.
https://stackoverflow.com/questions/6896746/is-there-a-broadcast-action-for-volume-changes

**Comment by sokolyaka** [comment]
ok, thanks!
