### ISSUE TITLE
Do action using voice command.

### ISSUE THREAD

**Issue by arpit-temi** [robotemi/sdk#170]
Hi,

I would like to give user a contact-less experience using Temi. By getting input using voice command and triggering events. I would like to ask Covid questions and user can answer Yes or No voice input. If user says yes then I would like to display different screen and if user says No then I would like to display alert dialog. 

What is the best approach to achieve this functionality.

Thank You

**Comment by lcgao** [comment]
Hi, please consider using [AsrListener](https://github.com/robotemi/sdk/wiki/Speech#asrListener) and [Override default NLU](https://github.com/robotemi/sdk/wiki/Speech#overrideNlu) to implement your idea.
