### ISSUE TITLE
[Request] Changing language programatically

### ISSUE THREAD

**Issue by evilmtv** [robotemi/sdk#173]
System/voice language change via API calls on the fly without reboot

**Comment by lcgao** [comment]
Hello, please create a new ticket for your request on [Zendesk](https://robotemi.zendesk.com/).
Thanks.

**Comment by evilmtv** [comment]
> Hello, please create a new ticket for your request on [Zendesk](https://robotemi.zendesk.com/).
> Thanks.

Will do
