### ISSUE TITLE
Is there a position status changed listener?

### ISSUE THREAD

**Issue by jiashengmatteo** [robotemi/sdk#176]
Hi, I was wondering if there is a listener similar to `OnGoToLocationStatusChangedListener` to track navigation status: START, CALCULATING, GOING, COMPLETE, ABORT when using `goToPosition(Position position)` instead of `goTo(String location)`.

Thank you in advance

**Comment by lcgao** [comment]
Also use `OnGoToLocationStatusChangedListener` .

**Comment by jiashengmatteo** [comment]
Ok, thank you. I saw the location is valued as "coordinates".
