### ISSUE TITLE
App Icon disappears from top bar when opening settings

### ISSUE THREAD

**Issue by LeoFauSR** [robotemi/sdk#177]
Hello,

I have seen issue #136 and I have integrated the code you suggested. When I close my app, the icon is still there in the top bar. But if I open the robot's settings after closing my app, the icon gets replaced by the settings icon and I can no longer access my app without running it again from android studio via the adb.

Is there a way to permanently secure the icon to the top bar or the screen of temi? 
Like I said, I already included the metadata mentioned in issue #136 in my manifest.

Thank you in advance.

Leo

**Comment by lcgao** [comment]
Hello, you can access your App in temi's apps(Contacts, Locations, Settings...).

**Comment by LeoFauSR** [comment]
The App is not being displayed in temi's apps. How can I change that?

**Comment by lcgao** [comment]
Sorry for missing the latest message. Please add following code as the child tag of `<application>` in AndroidManifest.xml:

``` xml
<meta-data
        android:name="com.robotemi.sdk.metadata.SKILL"
        android:value="@string/app_name" />
```

**Comment by LeoFauSR** [comment]
Thank you, I added the code in the wrong tag.
