### ISSUE TITLE
What structure does MapDataModel.mapImage.data obtained with getMapData() show?

### ISSUE THREAD

**Issue by ncostaka** [robotemi/sdk#178]
I am trying to collect map information that temi has.
What structure does MapDataModel.mapImage.data obtained with getMapData() show?

Specifically, I would like to use gotoPosition() to move to a specific location in the acquired mapImage.
What coordinates of the information obtained by mapImage's data are (x,y) specified in Position?
How do coordinates (x,y) associate with mapImage data?

**Comment by lcgao** [comment]
MapImage: https://github.com/robotemi/sdk/wiki/Locations#mapImage
