### ISSUE TITLE
How do I move temi out of the map area?

### ISSUE THREAD

**Issue by ncostaka** [robotemi/sdk#179]
I want to move the temi out of the map area that temi has.
If you try to move with goToPsition(),
  "The registration point could not be reached.
　 Make sure that the temi is in the mapped area and that the path is clear."is displayed.

How do I move temi out of the map area?

**Comment by lcgao** [comment]
Consider using [skidJoy()](https://github.com/robotemi/sdk/wiki/Movement#skidJoy).

**Comment by ncostaka** [comment]
Thank you in advance.
Using the sample code as a reference, I was available to move it out of the map area.

https://github.com/robotemi/sdk/blob/master/sample/src/main/java/com/robotemi/sdk/sample/MainActivity.java
