### ISSUE TITLE
How to use the onTelepresenceStatusChangedListener class?

### ISSUE THREAD

**Issue by Yusk1450** [robotemi/sdk#183]
I want to use the onTelepresenceStatusChangedListener.
However callEventModel.sessionId is empty at onTelepresenceEventChanged method.

The sessionId's Description in Github's documentation has been strikethrough.
https://github.com/robotemi/sdk/wiki/Users-&-Telepresence#onTelepresenceStatusChangedListener

Why dose it?
How to use the onTelepresenceStatusChangedListener class?

**Comment by lcgao** [comment]
Please use [OnTelepresenceEventChangedListener](https://github.com/robotemi/sdk/wiki/Users-&-Telepresence#onTelepresenceEventChangedListener) interface instead.

**Comment by Yusk1450** [comment]
Thanks!
Can I use OnTelepresenceEventChangedListener to get the event that the call was DECLINED ?

**Comment by lcgao** [comment]
Currently can't.

**Comment by luozhexin** [comment]
Can I use onTelepresenceStatusChangedListener class to monitor the call was DECLINED ?
