### ISSUE TITLE
.getLocations() returning an empty list

### ISSUE THREAD

**Issue by themissingCRAM** [robotemi/sdk#186]
I have some issues .getLocations, it returns an empty list for some reason even though in temicenter, I have explicitly entered my locations needed.  

![image](https://user-images.githubusercontent.com/60025340/112961424-eee43100-9177-11eb-83d6-d8c8e9634771.png)

Im not sure what I am doing wrong or if this is a bug. 
Hope someone could help.

**Comment by lcgao** [comment]
It is too early to invoke APIs after getting the instance of `Robot` immediately, please try to invoke function `getLocations()` after robot is ready([listen to OnRobotReadyListener](https://github.com/robotemi/sdk/blob/master/sample/src/main/java/com/robotemi/sdk/sample/MainActivity.java#L253-L264)).

**Comment by themissingCRAM** [comment]
Thanks that solved the problem
