### ISSUE TITLE
Alexa Skills For TEMI

### ISSUE THREAD

**Issue by thoshiwara** [robotemi/sdk#187]
Hi I am quite new to android development and was wondering if it is possible to develop and deploy custom Alexa Skills using the TEMI SDK? I haven't had any luck finding out how to go about this and would love any information / pointers in the right direction. Thank you for your time!

**Comment by lcgao** [comment]
Hi, there is no related API for Alexa in temi SDK, please try to get the information from Alexa official, thanks.
