### ISSUE TITLE
Preventing Sleep Mode

### ISSUE THREAD

**Issue by lulumiddel** [robotemi/sdk#192]
Hi, 
is there any way to prevent Temi from going into the Standby Mode? Currently, when using Zoom on Temi, Temi goes into sleep mode after 10 minutes of inactivity and it is rather difficult to get back into the conference. Is there a command such as: while Zoom.open -> prevent sleep mode? 
Thanks!

**Comment by lcgao** [comment]
Hi, there is no API of temi SDK to prevent going to Standby mode. How to disable Standby mode: Settings > General Settings> Standby - OFF.

**Comment by lulumiddel** [comment]
Thank you!
