### ISSUE TITLE
Unable to update temi to newest Launcher OS version

### ISSUE THREAD

**Issue by PureSecDR** [robotemi/sdk#200]
When checking for Software updates to install the newest Launcher OS for SDK version 0.10.77, instead of downloading a new version or saying temi is up to date, there is an error message saying 'Software Update error. Please try again'.

Current versions:
Launcher OS 14312
Robox OS 123.05

**Comment by lcgao** [comment]
Please create a ticket on [Zendesk](https://robotemi.zendesk.com/) for this issue and our Technical Support Engineer will follow up it.

**Comment by zjn0505** [comment]
Please contact temi customer support in temi app.
