### ISSUE TITLE
How do I access the infrared filter on the 13mp camera?

### ISSUE THREAD

**Issue by themissingCRAM** [robotemi/sdk#201]
How do I access the infrared filter on the 13mp camera?

I need to use `camera2` but I seemly can't find what `CameraCharacteristic` to use. 

I would like to do some computer night vision.

Unless I really need an external add-on which I don't have the budget for.

**Comment by zjn0505** [comment]
I am afraid there isn't such a filter on the temi Android camera.
The one that has red light is a ToF depth camera that used by the robot for algorithm, it is not exposed to Android.
