### ISSUE TITLE
How can we get video & voice data from device?

### ISSUE THREAD

**Issue by kotaIwanaga** [robotemi/sdk#204]
I plan to develop an application that releated to AWS service.
I would like to get video or vice data from Temi and then send it to AWS services.
How can we get these data from temi device and connect to AWS?
Is it possible to use aws-android-sdk ?

**Comment by zjn0505** [comment]
I think you should have no problem to access temi camera or microphone like on any other Android platform.
You would need to declare and request permissions for those access.
https://developer.android.com/training/permissions/requesting
