### ISSUE TITLE
Overide defualt NLU

### ISSUE THREAD

**Issue by Synizter** [robotemi/sdk#205]
I would like to use wake word (Eg. Hey Temi) and start speech recognizer instead of original one on temi
I have set overridden options in manifest and it still invoke Temi's speech recognizer. This is my manifest file

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.virachlabo.temikotlin">

    <uses-permission android:name="android.permission.INTERNET"></uses-permission>
    <uses-permission android:name="android.permission.RECORD_AUDIO"></uses-permission>
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.TemiKotlin">

        <meta-data
            android:name="com.robotemi.sdk.metadata.KIOSK"
            android:value="true" />

        <meta-data
            android:name="@string/metadata_open_without_internet"
            android:value="true" />

        <meta-data
            android:name="com.robotemi.sdk.metadata.SKILL"
            android:value="@string/app_name"
            ></meta-data>

        
        <meta-data
            android:name="@string/metadata_override_nlu"
            android:value="true" />

        
        <meta-data
            android:name="@string/metadata_override_stt"
            android:value="true" />

        
        <meta-data
            android:name="@string/metadata_override_conversation_layer"
            android:value="true" />

        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>`

**Comment by zjn0505** [comment]
Hi, I suppose your app hasn't been selected as Kiosk App.
Please take a look on this section [Override the ASR](https://github.com/robotemi/sdk/wiki/Speech#override-the-asr-)
