### ISSUE TITLE
How do make `#onRobotReady` invoke before `#onViewCreated` in my fragment?

### ISSUE THREAD

**Issue by CSmortal** [robotemi/sdk#206]
I saw #186 and gathered that `#onRobotReady` needs to be invoked before I can call `#getLocations` to get a non-empty result (My issue is that I'm getting an empty result from `#getLocations` when the program is run right after its installed, but there is no issue once I reopen the program)

I have some logic in my Fragment's `#onViewCreated` that needs the result of `#getLocations`, but the Fragment's `#onRobotReady` is only called after `#onViewCreated`. How do I go around this problem? And is it unnecessary to have multiple `OnRobotReadyListener`s?

**MainActivity.java**
![image](https://user-images.githubusercontent.com/67994626/122555637-21ae0f00-d06d-11eb-8d21-66f60ef68cd2.png)

I'm new to Android and fyi I'm using a navigation component here

**Comment by lcgao** [comment]
Actually you just need have one `OnRobotReady` listener at the very beginning of the App like the MainActivity(Launcher activity).
