### ISSUE TITLE
Conversational panel

### ISSUE THREAD

**Issue by kilmhd** [robotemi/sdk#208]
Hy,

I would like to know how to modify the conversational pannel. How to override the panel who appears on the screen when temi talks with us.

Could you help me?

**Comment by zjn0505** [comment]
Hi, you will need to first declare in the manifest file and select your app as kiosk app
https://github.com/robotemi/sdk/wiki/Kiosk-Mode

Then as the selected kiosk app in the system settings, your app can declare and override temi conversation layer.
https://github.com/robotemi/sdk/wiki/Speech#override-the-conversation-layer-

The last step is to listen to the conversation status change in your app and add your own reactions for each conversation state.
https://github.com/robotemi/sdk/wiki/Speech#onConversationStatusChangedListener

You can try this with your app. It will give you the maximum flexibility to customize the conversational panel.

Meanwhile we are actively working on other ways like simpler SDK interfaces and more UI options for developers and users to replace the default temi conversation appearance.
