### ISSUE TITLE
Defining different actions for same answers to different questions

### ISSUE THREAD

**Issue by LeoFau** [robotemi/sdk#210]
Hello,

I need Temi to ask multiple questions in several different situations. These all only need a yes or no answer from the user.
I have used the OnAsrResult-Method to define, what I want Temi to do for yes or no. I have also created separate methods just for asking the specific questions, as I need them multiple times in my app. But I need Temis actions to be dependend on which question was asked.

For example: Temi will be asking "Do you want to call your emergency contact?". If the user says yes, Temi will initiate the call.
If Temi asked "Do you want me to show you a new recipe?" and the user said yes, temi would have to react differently.

How can I achieve this difference? 

This is my OnAsrResult Method for how to react to the emergency contact question. But like I said, I would need the Robot to only do this, if he has been asked beforehand. Right now I could say "Hey Temi. Yes" and he would initiate the call. Which is obviously not what I want.

`@Override
    public void onAsrResult(final @NonNull String asrResult) {
        printLog("onAsrResult", "asrResult = " + asrResult);
        try {
            Bundle metadata = getPackageManager()
                    .getApplicationInfo(getPackageName(), PackageManager.GET_META_DATA)
                    .metaData;
            if (metadata == null) return;
            if (!robot.isSelectedKioskApp()) return;
            if (!metadata.getBoolean(SdkConstants.METADATA_OVERRIDE_NLU)) return;
        } catch (PackageManager.NameNotFoundException e) {
            e.printStackTrace();
            return;
        }
        if (asrResult.equalsIgnoreCase("Yes")) {
            robot.speak(TtsRequest.create("Initiate the call to your emergency contact.", true));
            robot.finishConversation();
            robot.startTelepresence(contactName, contactID);
        } else if (asrResult.equalsIgnoreCase("No")) {
            robot.speak(TtsRequest.create("Okay. Going to home base", true));
            robot.finishConversation();
            robot.goTo("home base");
        } else {
            robot.askQuestion("I'm sorry I didn't understand. Can you repeat that?");
        }
    }`

**Comment by zjn0505** [comment]
When temi asks "Do you want to call your emergency contact?" or "Do you want me to show you a new recipe?".
You can create a context like "emergency_call" or "check_recipe" for this conversation.
Only then your app will react to "Yes" and "No" with corresponding actions.

NLP engines like DialogFlow provide such concept https://cloud.google.com/dialogflow/es/docs/contexts-overview
