### ISSUE TITLE
is it possible to start a conversation with a user without having to use the wakeup word?

### ISSUE THREAD

**Issue by ashwindevadiga** [robotemi/sdk#215]
is there a way to programatically start the conversation without having to ask a question or wakeup?

**Comment by leslieam** [comment]
You can wakeup with temi's SDK wakeup API. But you must define how will you trigger it. 
Maybe trigger it when the camera detects a person.

https://github.com/robotemi/sdk/blob/master/docs/sdk/com.robotemi.sdk/-robot/wakeup.md
