### ISSUE TITLE
Face recognition 

### ISSUE THREAD

**Issue by arpit-temi** [robotemi/sdk#217]
Hi Team,

We are building app that Temi can go to person room and recognize the face of that person and display picture of family members and click on the picture to call that person. Do you think is it possible using the Temi SDK.  I have question that how do we associate contacts to that person. Can I have Temi SDK functionality that I can use in my app?

According to my research I show that in SDK **Face Recognition** guide.  

**Note**: we know that it requires the contact on Temi center and upload pictures of the person.

**Comment by lcgao** [comment]
temi SDK's face recognition will return the user ID of the recognized face, so your App can establish a link between the user ID and his family members. Show the pictures of family members(contains user ID as well) once the particular user is recognized. The key point of this requirement is building the relationship of family by code logic.

Functions or interfaces that may be used:

https://github.com/robotemi/sdk/wiki/temi-Center#startFaceRecognition
https://github.com/robotemi/sdk/wiki/temi-Center#onFaceRecognizedListener
https://github.com/robotemi/sdk/wiki/Users-&-Telepresence#getAllContact
https://github.com/robotemi/sdk/wiki/Users-&-Telepresence#startTelepresence

Hope this helps.
