### ISSUE TITLE
OnMovementStatusChangedListener not triggering  "goto" changes

### ISSUE THREAD

**Issue by WoutDemeyere** [robotemi/sdk#222]
Hello, when using the OnMovementStatusChangedListener it triggers if you use the skidJoy() or turnBy() method but not when the robot is going to a POI or sees an obstacle etc...

Are there certain permissions required for this function?

**Comment by lcgao** [comment]
Hello, for going to a specific location or position we provided another listener to listen to the status of movement: https://github.com/robotemi/sdk/wiki/Locations#onGoToLocationStatusChangedListener.
