### ISSUE TITLE
Kiosk Mode  issues.

### ISSUE THREAD

**Issue by themissingCRAM** [robotemi/sdk#234]
Why doesn't robot.setKioskModeObn(true) works when boot up my app?
```
        //Permissions checking and request codes
        if (ContextCompat.checkSelfPermission(requireContext(),
                Manifest.permission.READ_EXTERNAL_STORAGE) !=
                PackageManager.PERMISSION_GRANTED)
            requestPermissionLauncher.launch(Manifest.permission.READ_EXTERNAL_STORAGE);
        else if (robot.checkSelfPermission(Permission.SETTINGS) != Permission.GRANTED) {
            robot.addOnRequestPermissionResultListener(this);
            robot.requestPermissions(
                    new ArrayList<>(Collections.singleton(Permission.SETTINGS)),
                    Permission.GRANTED
            );
        }
  Log.d(TAG, "MainFragment onCreate kioskMOde and isSelectedKioskApp Check: " + robot.isKioskModeOn() + robot.isSelectedKioskApp());
        if (!robot.isKioskModeOn() || !robot.isSelectedKioskApp()) {
            robot.setKioskModeOn(true);
            robot.requestToBeKioskApp();
            Log.d(TAG, "MainFragment onCreate kioskMOde and isSelectedKioskApp Check: " + robot.isKioskModeOn() + robot.isSelectedKioskApp());
        } //do not put as if else
```

Also even though I have granted Settings permission already, it also goes into the else if block as it is not granted. Also onRequestPermissionResults didn't run in my code.

It is frustrating that these codes seems glitchy.

Is there a reason why I have to access the goToSpeed and toggling of the billboard through this this kiosk permission? Why can't it be just Settings?

Is this a bug? Or some internal settings I did not configure properly?

**Comment by lcgao** [comment]
If you just want to request your App to be the selected Kiosk mode App, using `robot.requestToBeKioskApp()` is enough, but the `meta-data` is necessary also for that.

``` xml
<meta-data
    android:name="com.robotemi.sdk.metadata.SKILL"
    android:value="@string/app_name" />

<meta-data
    android:name="com.robotemi.sdk.metadata.KIOSK"
    android:value="TRUE" />
```
After that, the system will pop up a dialog box after the method is called. After clicking the "Allow" button, your skill will become the currently selected Kiosk skill.

Actually `onRequestPermissionResults` is not the callback method of temi SDK and it belongs to Android SDK, you should implement [`OnRequestPermissionResultListener`](https://github.com/robotemi/sdk/wiki/permission#onRequestPermissionResultListener) to listen to the permission granted status. More information for the temi permission please check the documentation and the sample code.

We want that there is only one App could modify the system settings at a time so Kiosk permission is required for that.

**Comment by themissingCRAM** [comment]
hmm, 

My AndroidManifest.xml have do have such xml codes already and I have already implemented OnRequestPermissionResultsListener and also the add and remove statements.

I put my codes above in MainActivity onResume, I did put in my MainFragment onCreateView before. Maybe there is something wrong with the placement here. Those codes gave me double or triple Kiosk permission requests on the very first start up of the app on temi.

I wonder if  Settings permission works with ActivityResultLauncher. I used this to get the external storage permission.

Okay enough of my random thoughts and guesses, I will try to read the sample codes even though Im working with Java.

**Comment by themissingCRAM** [comment]
Thank you so much for 1) no more double kiosk permission request.

I could have also use 2) too but I think my stakeholders may want an actual exit function.
