### ISSUE TITLE
Start the patroling & mapping programatically 

### ISSUE THREAD

**Issue by Alex-Beh** [robotemi/sdk#239]
May I know what is the API to trigger the patroling task? Thanks.

**Comment by lcgao** [comment]
No API to trigger patroling task directly, but developers could implement a patrol function by following APIs,
1. [`goTo(String location)`](https://github.com/robotemi/sdk/wiki/Locations#goTo)
2. [`OnGoToLocationStatusChangedListener`](https://github.com/robotemi/sdk/wiki/Locations#onGoToLocationStatusChangedListener)

Hope this helps.

**Comment by Alex-Beh** [comment]
Thanks, this is my backup plan also. Can we start the mapping remotely?

**Comment by Alex-Beh** [comment]
@lcgao friengly ping :)

**Comment by lcgao** [comment]
Neither.
