### ISSUE TITLE
Disable tracking function

### ISSUE THREAD

**Issue by MiRobotic** [robotemi/sdk#242]
Hi

We have customize a app and one function is required to detect person and greeting. So the greet mode is on. We disable the setting tracking people function in setting. However, the robot still tracking people when it detect person.

How to disable tracking people but greet mode still on

Thanks

**Comment by lcgao** [comment]
Hi, you can configure this on [temi Center](https://center.robotemi.com/):

![1636939521(1)](https://user-images.githubusercontent.com/16516441/141708388-64827aa5-d5eb-4204-8d97-bddfaac813e3.jpg)

**Comment by MiRobotic** [comment]
> Hi, you can configure this on [temi Center](https://center.robotemi.com/):
> 
> ![1636939521(1)](https://user-images.githubusercontent.com/16516441/141708388-64827aa5-d5eb-4204-8d97-bddfaac813e3.jpg)

Hi, I still need greet mode but i dont want to track a person. As everytime robot track a person, then it moving along. I already disable the button you mention above. However the robot still tracking person

Thanks

**Comment by lcgao** [comment]
Shouldn't be like that, could you please shoot a video for it?

**Comment by leslieam** [comment]
How did you trigger user tracking, with a touch on the main button on the head?
This will trigger following not user tracking.

User tracking is trigger in greet mode. You need to configure the greet mode and wait the robot enter greet mode and then walk toward it to be in front of the robot.
