### ISSUE TITLE
Greet mode - turn on and turn off via code

### ISSUE THREAD

**Issue by MiRobotic** [robotemi/sdk#247]
hi

In temi center there is function to manual turn on and turn off the Greet mode. We are working on one app  and want to stop greet mode according to time schedule without going to temi center to turn on and off the greet mode. Any API or SDK with this function

Thanks

**Comment by lcgao** [comment]
Hi, use [`setMode(Mode.DEFAULT)`](https://github.com/robotemi/sdk/wiki/Utils#setMode) to turn off the Greet mode.
