### ISSUE TITLE
setGoToSpeed not working

### ISSUE THREAD

**Issue by Alex-Beh** [robotemi/sdk#248]
Hello, I have tried to use the API setGoToSpeed() but it is not working.

Language: Java

```
  SpeedLevel newspeedlevel = SpeedLevel.SLOW;
  sRobot.setGoToSpeed(newspeedlevel);
  Log.i(TAG, "[setSpeed] setSpeed: "+newspeedlevel);
  Log.i(TAG, "[setSpeed] currentSpeed: "+sRobot.getGoToSpeed().toString());
```

Current printout is:
```
I/MAIN: [setSpeed] setSpeed: SLOW
I/MAIN: [setSpeed] currentSpeed: HIGH
```

Expected printout is:
```
I/MAIN: [setSpeed] setSpeed: SLOW
I/MAIN: [setSpeed] currentSpeed: SLOW
```

**Comment by Alex-Beh** [comment]
@zjn0505 @lcgao @hermanShai friendly ping

**Comment by lcgao** [comment]
Sorry for the delay, please check below things:
1. App has the Settings permission
2. As the selected kiosk App and as the home screen
