### ISSUE TITLE
"Follow Mode" Temporarily Disabled 

### ISSUE THREAD

**Issue by jasonjabbour** [robotemi/sdk#252]
Hi!

I'm having trouble with Temi's follow mode. The notification center shows the following message: 
"Follow Mode" temporarily disabled. Try to restart the robot. If not resolved, contact Help Desk. 

Whenever I put Temi in "Follow Mode" it gets stuck in the "Calculating" state. Is anyone familiar with this issue and any potential fixes? I have restarted Temi several times and I am connected to Wifi. 

Thank you!

**Comment by leslieam** [comment]
Hi, 
Please contact the help desk with
Videos of the symptom,
SN of the robot,
Version of the launcher,
Version of the Robox

https://www.robotemi.com/helpdesk/
