### ISSUE TITLE
toggleNavigationBillboard doesn't work

### ISSUE THREAD

**Issue by seungwon-yoo** [robotemi/sdk#255]
I use this function but still navigation billboard is showing. what should I do?

**Comment by lcgao** [comment]
Hi, the required permissions for this function are "Selected kiosk"(Home Screen>Application) & "Settings", so request the permissions before calling this function.

https://github.com/robotemi/sdk/wiki/Utils#toggleNavigationBillboard
https://github.com/robotemi/sdk/wiki/Kiosk-Mode#requestToBeKioskApp
https://github.com/robotemi/sdk/wiki/permission#request-skill-permissions
