### ISSUE TITLE
New ADB secure system requires internet

### ISSUE THREAD

**Issue by evilmtv** [robotemi/sdk#260]
Is it possible to have it work without internet access on Temi?

Currently gives 'error 02' when attempting on a no-internet-access network

**Comment by zjn0505** [comment]
Does it work when there is internet connection?

**Comment by evilmtv** [comment]
> Does it work when there is internet connection?

Hey, yeah it works fine when I'm on a wifi with internet. However it shows that error message on the auth URL if Temi is on a wifi without internet.

**Comment by evilmtv** [comment]
> Can you leave the serial number of the robot?

Do you still require the serial number?

**Comment by zjn0505** [comment]
No need if you confirm that it can work with network.
We will try to improve adb secure connection experience when there is not network in the following releases.
