### ISSUE TITLE
ADB connection requires Password

### ISSUE THREAD

**Issue by LagrouCedric** [robotemi/sdk#261]
While trying to establish a ADB connection with temi, there was a new screen pop up that requires us to make connection with a password. This is probably part of the new secure ADB, but now we can't make connection to Temi, all 3 options to connect ( curl, http, adb connect) give timed out or host not found errors.

Is there another way of making connection to Temi with ADB? or another way of uploading apps onto the robot?

**Comment by lcgao** [comment]
Unfortunately there is not another way to connect ADB, please provide the SN and the screenshoot for the issue to us, thanks.

**Comment by LagrouCedric** [comment]
We made connection using a 4G hotspot, i think the 5556 port is blocked on our DNS server and so we could not establish connection.
