### ISSUE TITLE
TTS with no Wifi

### ISSUE THREAD

**Issue by Ryan-Lee-2000** [robotemi/sdk#262]
Is it possible to use the TTS without Wifi? The location I'm running my Temi at the moment doesn't have stable Wifi. At the moment the TTS will fail whenever the Wifi disconnects.

**Comment by lcgao** [comment]
No, currently TTS is generated on the server side so the internet is necessary. However if you have any local TTS solutions you can consider overriding the original TTS of temi by SDK: https://github.com/robotemi/sdk/wiki/Speech#overrideTts.
