### ISSUE TITLE
Using Speech Synthesis Markup Language (SSML) in TTS

### ISSUE THREAD

**Issue by piccinnigius** [robotemi/sdk#271]
Hi,

seems that TEMI is using Google  TTS, and works well with simple text.
there is any way to use  SSML? as reported here [reported here https://cloud.google.com/text-to-speech/docs/ssml](https://cloud.google.com/text-to-speech/docs/ssml)

Thanks so much

**Comment by lcgao** [comment]
Hi, SSML is currently not supported.
