### ISSUE TITLE
get all sequences show exception

### ISSUE THREAD

**Issue by william-1415** [robotemi/sdk#276]
hi,
I try to get the sequence ID by SDK sample " sdk:0.10.79 ", and already grant permission, but not work then show an error exception.

" onSdkError:SdkException(code=500,message=Get Sequences failed) "

thankyou !!

**Comment by lcgao** [comment]
Hi, could you please provide the serial number of temi? You can find the serial number at Settings->About->Serial Number.

**Comment by zjn0505** [comment]
We are checking get all sequences API. We will let you know once it is fixed.

**Comment by zjn0505** [comment]
We've deployed the fix. Please try again with this SDK interface.

**Comment by william-1415** [comment]
now I can get sequence ID, thank you
