### ISSUE TITLE
setLocked(boolean) and isLocked() not working

### ISSUE THREAD

**Issue by sduenasg** [robotemi/sdk#277]
Hi again, we are trying to toggle locked mode (password lock) via the SDK using these:

https://github.com/robotemi/sdk/wiki/Utils#setLocked

But it isn't working, both functions show up as unresolved references in Robot.getInstance(). Is there any workaround for this?

**Comment by lcgao** [comment]
Hi, this function is supported from version 0.10.74 as the wiki documentation mentioned. So please update the SDK version in app/build.gradle and sync to use this function.

**Comment by sduenasg** [comment]
We are using the latest sdk 0.10.79 at the moment. I've seen in the sample app that there is a direct way to read/write Robot.getInstance().locked variable. I'll try tomorrow (I'm not with Temi today) and close this issue if it works. Thanks!

**Comment by sduenasg** [comment]
it is working, thanks!
