### ISSUE TITLE
Overview of user peer-IDs

### ISSUE THREAD

**Issue by LeoFau** [robotemi/sdk#278]
Hello,

is there anywhere I can access the peer-ID of every user without displaying all the user information programmatically?
Maybe in the temi center or in the app?
I couldn't find it so far and would like to set a few fixed contacts for telepresence.

Thank you in advance.

**Comment by lcgao** [comment]
Hello, do you want to get peer-IDs of all user programmatically? If yes, using [`Robot.getInstance().getAllContact()`](https://github.com/robotemi/sdk/wiki/Users-&-Telepresence#getAllContact).

**Comment by LeoFau** [comment]
Hello,
as stated in the original question, I would like to find this information without integrating this into my code. 
I thought that this information is probably available elsewhere. For example in the temi center or the temi app. As admin I thought I would be able to access this information somewhere without running this code (which I know works, as I have used it before, but I am looking for an alternative).

Thank you

**Comment by lcgao** [comment]
Hello, please open a ticket for this new request on Zendesk. Thanks.

**Comment by zjn0505** [comment]
@LeoFau 
As this is not a user oriented feature, and the contact peer id is quite meaningless to be displayed on UI, we cannot show it on temi center or mobile for regular user access.

However, it is accessible for developers to find it out on temi center.

I would suggest to use temi center with browser dev tool opened, open the members page of a robot, and search in the network tab with filtering of "members".

`clientId` there is what we are looking for.

![image](https://user-images.githubusercontent.com/6925920/163551895-16ae4304-17a5-4159-b741-1cd40509e1ac.png)

**Comment by LeoFau** [comment]
Perfect, thank you!
