### ISSUE TITLE
wakeup is not working 

### ISSUE THREAD

**Issue by iamkhan001** [robotemi/sdk#280]
Hi there, 

I'm working on chat application using temi. here for STT, everytime user needs to say wakeup word. 
but I want to listen to user without using wakeup word while user is on chat screen 

I'm trying to use ` Robot.getInstance().wakeup();` but its not working for me.

is there any extra code or permission i need to add in app?

**Comment by lcgao** [comment]
Hi, sorry for the late reply, so have you solved this?
