### ISSUE TITLE
why bindService is flase

### ISSUE THREAD

**Issue by jackk2347** [robotemi/sdk#287]
![image](https://user-images.githubusercontent.com/55519967/172135347-289bc57c-4b3a-4320-99da-1e9bd0477b3f.png)

**Comment by lcgao** [comment]
It means SDK didn't conntect with temi Launcher successfully. The App using temi SDK should run on real temi robot instead of Android simulator.

**Comment by jackk2347** [comment]
Oh! you mean that if the apps is running in the temi is working? it cannot running in virtual device?

**Comment by lcgao** [comment]
Yes, actually temi SDK dependents on temi Launcher App, so temi Apps cannot run on a virtual device that doesnot install temi Launcher.

**Comment by jackk2347** [comment]
Also, i want to ask that the used api is  just need implementation 'com.robotemi:sdk:0.10.80' right?

**Comment by lcgao** [comment]
Yes, we just provid this library.
