### ISSUE TITLE
how to use the asrlistner function , can give me some example ?

### ISSUE THREAD

**Issue by jackk2347** [robotemi/sdk#289]
how to use the asrlistner function , can give me some example ?
for example : how to addAsrListener and use the  onAsrResult function? 
![image](https://user-images.githubusercontent.com/55519967/172579735-fd2da548-3716-490a-a2fd-189b2673ef9c.png)

**Comment by lcgao** [comment]
Please refer to the Sample code [here](https://github.com/robotemi/sdk/blob/master/sample/src/main/java/com/robotemi/sdk/sample/MainActivity.kt).

**Comment by jackk2347** [comment]
however , where is received the voice message?

**Comment by lcgao** [comment]
The callback method `onAsrResult()` you implements from the `AsrListener`.

**Comment by jackk2347** [comment]
Ok, the onAsrResult() is received the voice meassge  first and response it? However , i don know how to received the voice message first .

**Comment by lcgao** [comment]
If you register the AsrListener correctly, the method onAsrResult() will be invoked by SDK and your App will be able to receive the voice message from there.

**Comment by jackk2347** [comment]
Ok , thank a lot . it is working

**Comment by jackk2347** [comment]
Also, i want to ask that can i set the voice message first and then wake up the temi?
