### ISSUE TITLE
how to check tts is completed. 

### ISSUE THREAD

**Issue by jackk2347** [robotemi/sdk#297]
how to check tts is completed.  Since i want to check tts is completed then call the wakeup function.

**Comment by jackk2347** [comment]
Such as : Speak hello . Then the temi response me to Hello , Can i help you. how to know the response is ended . i want to wait the  response then call the wakeup function .

**Comment by zjn0505** [comment]
TtsListener:
https://github.com/robotemi/sdk/wiki/Speech#ttsListener
Example
https://github.com/robotemi/sdk/blob/master/sample/src/main/java/com/robotemi/sdk/sample/MainActivity.kt#L946-L949
