### ISSUE TITLE
Kiosk mode and built-in orders issues

### ISSUE THREAD

**Issue by sduenasg** [robotemi/sdk#299]
Hello. In order to activate Greet mode from our app, we are activating Kiosk Mode too (sdk restriction), using the sdk. We have all the necessary permissions to do this, and both kiosk mode and greet mode work.

Thing is, when Kiosk mode is enabled (our app is Temi's home screen) the robot doesn't respond to any built-in orders (like "go to") nor any other Q&A queries (the ones we define in Temi Center). After saying "hey temi" and the order, it just sits there moving its eyes up and down. Disabling kiosk mode solves this issue. But we have to activate kiosk mode to be able to activate greet mode from the app, which is one of our client's requirements.

Any ideas? Is there any way to skip this "kiosk mode on" requierement on greet mode? i mean, I can activate Greet mode from Temi Center without kiosk mode being enabled... the client just wants to activate greet mode from the app itself

**Comment by zjn0505** [comment]
In 128 version with temi launcher app 16398, turn on Greet Mode from SDK cannot bypassed and requires kiosk mode.

**Comment by sduenasg** [comment]
Thank you. For some reason (probably testing stuff), our app was overriding NLP. It's fixed now.
