### ISSUE TITLE
Is SDK robot.navigationSafety incorrect?

### ISSUE THREAD

**Issue by kakeung** [robotemi/sdk#303]
After I call `robot.navigationSafety = SafetyLevel.MEDIUM`, the setting is changed on TEMI setting page. However, I get the value from `robot.navigationSafety` is still `SafetyLevel.HIGH`.

temi SDK version: 0.10.80
launcher version: 16398-usa
robox version: 129.06
fireware version: 20220622.200917

**Comment by zjn0505** [comment]
Thanks for pointing out.
This should be a bug we introduced last year in the 126 version.
