### ISSUE TITLE
Problem with the recognition camera in temi V3.

### ISSUE THREAD

**Issue by eSalto** [robotemi/sdk#308]
Hello, we have a problem with the recognition camera. When we activate startFaceRecognition we don't find the person in temi V3 (Android 11), instead in temi V2 (Android 6) it works and finds the person. We have uploaded the images of the person so that it is correctly recognized in the TEMI CENTER but it always returns the empty list.

We have verified that we have not installed the temi V3 incorrectly, but we believe that it works because the video call does work well.

**Comment by zjn0505** [comment]
Face Recognition functions currently doesn't work on the V3 robots running temi launcher version 16398.
This is a pioneer version we sent out to our key customers to get early hands on, meanwhile we are still doing a lot of work for its features.
Face recognition will be supported in the next software release on V3 robot.
