### ISSUE TITLE
Speech-To-text after the WakeupWord trigger

### ISSUE THREAD

**Issue by lcarnevale** [robotemi/sdk#31]
Hello all,

This issue partially covers the topic discussed into the issue #24, which is currently closed.

I have tried the sample application into this SDK and I have understood how to use the _WakeupWordListener_ to activate the Speech Recognition of Temi. Therefore, I followed the tutorial posted into the issue #24 to setup an intent through the Temi's Settings page and implement my code into _onNlpCompleted_. This works pretty fine.

What I have wondered is why this tutorial involves a manual process and therefore I have few questions:
1. may I use a programmatic approach to setup the intents?
2. may I access the Speech-To-Text, which is available into _onNlpCompleted_, just after the wake up? I mean, I would like to have a channel which transcribes what the user says to the robot after the wake up. Is an API call available for accomplishing this goal?

Best,
Lorenzo.

**Comment by ramisaban1** [comment]
Hello,

Thank you for your concern, the Local NLP functionality was always intended as something temporary. This was implemented in order to give developers something to work with until February which is when we plan to allow usage of a custom DialogFlow NLP Agent.

Best,
Rami

**Comment by ramisaban1** [comment]
Let me know if you have any additional questions or concerns

**Comment by PureSecDE** [comment]
> This was implemented in order to give developers something to work with until February which is when we plan to allow usage of a custom DialogFlow NLP Agent.

Hello @ramisaban1 ,

is it still planned to make it possible to use an own DialogFlow-Agent and is there already an approximate date when you can expect this?

Best,
PureSecDE

**Comment by nicolacorriero** [comment]
> Hello,
> 
> Thank you for your concern, the Local NLP functionality was always intended as something temporary. This was implemented in order to give developers something to work with until February which is when we plan to allow usage of a custom DialogFlow NLP Agent.
> 
> At this point in time, there is no programmatic approach to setting up intents. Since we are working on releasing this to the public as quickly as possible, we are focussing mainly on its' development, and not improving the current Local NLP.
> 
> Regarding a channel to get what the user says to the robot after the wake-up, you can use `NlpResult.resolvedQuery` within the `onNlpCompleted` listener which returns a `string` containing the command given by the user.
> 
> Best,
> Rami

Hello @ramisaban1 
any news regards custom DialogFlow NLP Agent?

**Comment by nicolacorriero** [comment]
Hello @ramisaban1 
any news regards custom DialogFlow NLP Agent?

**Comment by nicolacorriero** [comment]
Hello @ramisaban1 
any news regards custom DialogFlow NLP Agent?
