### ISSUE TITLE
DialogFlow after the WakeupWord trigger

### ISSUE THREAD

**Issue by lcarnevale** [robotemi/sdk#32]
Hello all,

I activated the "_Hey Temi_" wake up word through the Temi's Settings page. Does it use DialogFlow to answer after the wake up word trigger? If yes, may I setup my private DialogFlow agent, replacing the existing one?

Best,
Lorenzo.

**Comment by ramisaban1** [comment]
Hello,

Access to setting up a custom NLP Agent on temi will be posted to the public in February through a software update on _temi_.

Best,
Rami

**Comment by ramisaban1** [comment]
Feel free to get back in touch if you still have any concerns!
