### ISSUE TITLE
TEMI browser cannot open a certain website (SSL cert related?)

### ISSUE THREAD

**Issue by Ant23564** [robotemi/sdk#322]
We added an Q&A to open the following website in TEMI browser: https://www.cccmkckos.edu.hk/
But the browser failed to open it, the window is blank.

Then we added another Q&A to open Google in order to ensure the browser is running fine and we can further open any website to test.  It is strange that the browser only fails to open the above URL, which could be opened on any other desktop and mobile browsers.

That site's SSL cert was signed by Starfield Root Certificate Authority - G2.  Further investigation found that if we disabled the 3 Starfield root CA certs in Settings, go back to the previous screen, and then re-enable those CA certs, sometimes the website could then be opened.

The strange thing is the Starfield Technologies' website (https://www.starfieldtech.com/) was signed by the same root CA and intermediate CA.  TEMI browser has no problem opening Startfield's website.

**Comment by zjn0505** [comment]
Hi, I suppose you are using temi V3 with browser app version 1.6(7)

The browser version 7 in the 128 release wasn't fully adapt to V3. We will fix it in 129 release.

You can try this candidate version for 129 release. Browser [Version 1.8(9)](https://app.bitrise.io/app/b445783ba44a3c71/build/52244f4d-27bb-4419-8a38-23d89ddae034/artifact/5f9bf2ae1b978ce2/p/589521e31cc123c9bf9ed7b2dcac90a3).

I tested with this 1.8(9) version to load the site, and it works.

I guess the reason behind is http cleartext traffic and not related to SSL.

Cleartext traffic is not supported by default after Android 7, and Browser version 1.6(7) didn't declare `usesCleartextTraffic=true`.

That site has some CSS resources with http schema and couldn't be loaded with that browser.
