### ISSUE TITLE
Temi v2 compatibility with SDK v1.129.x

### ISSUE THREAD

**Issue by jiashengmatteo** [robotemi/sdk#325]
Hi, we have a Temi v2 with Robox OS v128.08 and firmware v20201216.154352.
Is it compatible with new SDK v1.129.x? 
If so, which features are compatible and which are not?

**Comment by zjn0505** [comment]
SDK 1.129.x can be used with temi V2

All the APIs from 0.10.80 shall be working in 1.129.x. 

But APIs added or changed in 1.129.x and later versions will require a v129 and higher version temi OS.

**Comment by jiashengmatteo** [comment]
Ok, thank you for the information
