### ISSUE TITLE
Is there a function in the SDK that does the mapping?

### ISSUE THREAD

**Issue by eSalto** [robotemi/sdk#329]
Hi,
I am trying to create a view in my app to map. And I was wondering if the mapping could be started from some SDK function.

Thanks!

**Comment by zjn0505** [comment]
You can use this function to launch temi's map editor.

https://github.com/robotemi/sdk/wiki/Utils#startPage

Display a dynmaic map from SDK is quite resource heavy, and there isn't an SDK function to start mapping.

**Comment by eSalto** [comment]
Okey, thanks.
