### ISSUE TITLE
Confirming if Multi-Floor support is available for Temi V1

### ISSUE THREAD

**Issue by lohwenxin** [robotemi/sdk#346]
Hello, 

I am raising this issue as I am trying to setMultiFloorEnabled for Temi V1.

When I call the [setMultiFloorEnabled](https://github.com/robotemi/sdk/wiki/Locations#setMultiFloorEnabled) method and print isMultiFloorEnabled, I get a null result.
![image](https://user-images.githubusercontent.com/80497924/203506712-1499ccf5-6e57-452b-8cdc-5d6021547c26.png)
![image](https://user-images.githubusercontent.com/80497924/203507147-d9462e82-8301-41b3-aa96-f61102f6913d.png)

As per the requirements of the setMultiFloorEnabled method, I have MAP and SETTINGS permissions and my temi version is greater than 1.129.0. 
![image](https://user-images.githubusercontent.com/80497924/203506434-cca369c3-2ece-469f-a433-d621493c9e57.png)
![image](https://user-images.githubusercontent.com/80497924/203506499-0a54edbf-5f71-4042-a5a1-f751e3c9a1e8.png)

The Multi-Floor support was included in the 1.129.0 release, but I noted that the release says that this version is only applicable for Temi V3. **Could I re-confirm that there is no Multi-Floor support for Temi V1?** Subsequently, may I check if support for Multi-Floor will be available for Temi V1 and V2 in further releases?
![image](https://user-images.githubusercontent.com/80497924/203506167-0bb3c499-248b-47a5-8598-7cce23f76c8a.png)

Thank you!
Wen Xin

**Comment by zjn0505** [comment]
Major version updates won't be available for temi V1 and V2, only hotfixes upon 128 version for potential critical bugs and broken features would be provided.

Most of the changes in temi SDK will require a comptible version of temi launcher, multifloor is for V3 robot on 129 version.

**Comment by lohwenxin** [comment]
Alright, thank you for the clarification :+1:
