### ISSUE TITLE
Add Contacts by SDK

### ISSUE THREAD

**Issue by eSalto** [robotemi/sdk#382]
Hi, that contacts can be added by SDK? If not, what do you plan to add in future versions?

thanks

**Comment by zjn0505** [comment]
There is no plan to add it yet.

Can you describe your use case? Maybe we can help in another way.

**Comment by eSalto** [comment]
In our use case we want to be able to add contacts through our application. Right now we show the list of contacts that Temi can call, but if the user wants to add new contacts, he has to let us know before so we can add them from the temi center.

**Comment by zjn0505** [comment]
We don't have this in the design yet, and probably won't allow apps to directly modify temi or user resource in the future.

There is a definition of role in temi's organization, you may add the temi users as Collaborator in the organization, so they will only have access to robots they were delegated to with appropriate permissions.

**Comment by eSalto** [comment]
All right, we'll close the issue
