### ISSUE TITLE
Temi orientation problem when loading map in lift

### ISSUE THREAD

**Issue by Magiccofee** [robotemi/sdk#383]
I have been trying to have the temi load map when it is travelling between floors on the lift. It is able to complete the map load before the lift doors open, however often the orientation will be 180degrees off from its actual state. It seems that the robot only loads the map with the correct orientation when the lift doors are open by the time the loading is complete. Is there a way to solve this issue.

I am using a temi V2 with launcher OS 16400.

**Comment by zjn0505** [comment]
Please check this method `loadMapWithPosition`, it takes a parameter of `position` with x, y, and yaw.

This position shall be the postion of location of the new floor, and when you calling this method, please make sure robot is right on that location with correct direction.


In practice, for example, on every floor, you can build the map a location named "elevator", which is the same physical spot in the elevator cabin, and robot is pointing to the same direction, e.g. the door of elevator.

When you robot entering the elevator from other floors, it shall go to the exact that location and start to load the map of target floor with the method of `loadMapWithPosition` and using `elevator` postion of target floor.

Then it shall behaves as desired, map of target floor is loaded, and robot pointing to the correct direction.


---

On the algorithm side, there are some optimizations made when going to the location of "elevator". i.e. it will be more patient and accurate, also higher tolerance for the crowded situatation when the robot is surrounded by people. So a trick is to name the location "elevator" if your robot is not entering the elevator well.
