### ISSUE TITLE
Temi ADB Connection Issue on temi version 115.64

### ISSUE THREAD

**Issue by muhadnanafridi** [robotemi/sdk#40]
I tries several networks to connect my android studio with temi  but it is giving me this error on command "adb connect 172.18.20.152:5555"

"cannot connect to 172.18.20.152:5555: No connection could be made because the target machine actively refused it. (10061)"

**Comment by ramisaban1** [comment]
Hello @muhadnanafridi,

Most of the time this type of thing happens if **ADB Port Opening** wasn't pressed under **Settings -> _temi_ Developer Tools -> ADB Port Opening**. If this still doesn't work, please make sure both the computer you are trying to connect from as well as _temi_ are connected to the same Wi-Fi network.

Best,
Rami

**Comment by datablackhole** [comment]
Same issue faced by me. I have tried to connect via adb using multiple computers and also tried different networks where i made sure I both the robot and computer were on the same network...

I've noticed Temi technician tools menu which asks for a password... is there anything in that menu that could be of help ?

**Comment by lcarnevale** [comment]
Hello,

I experienced a closing of the ADB Port after a while. Therefore, even if I already opened it and connected, I had to open again.

Best,
Lorenzo.

**Comment by ramisaban1** [comment]
Are you tapping **ADB Port Opening** after connecting to the network on temi? The only reason the "device" (meaning temi) would refuse a connection is if the port wasn't opened.

**Comment by datablackhole** [comment]
> Are you tapping **ADB Port Opening** after connecting to the network on temi? The only reason the "device" (meaning temi) would refuse a connection is if the port wasn't opened.

Several times.

**Comment by muhadnanafridi** [comment]
Yes I am tapping ADB PORT Opening but its not working for me . From last 1 week i am unable to work on Temi . 

    On Tuesday, December 24, 2019, 09:23:14 AM GMT+4, datablackhole <notifications@github.com> wrote:  
 
 

Are you tapping ADB Port Opening after connecting to the network on temi? The only reason the "device" (meaning temi) would refuse a connection is if the port wasn't opened.


Several times.

**Comment by ramisaban1** [comment]
Hello,

I know this seems frustrating, and you definitely tried this, but please try connecting both devices to a new network. I am also attaching a video demonstrating the connection process.

ADB Connecting Tutorial Video:
https://drive.google.com/file/d/1NaQda3udF-LrXmJ6pisSwDZ2XUCD_2d5/view?usp=sharing

Best,
Rami

**Comment by uglyduck2019** [comment]
We had two Temi on hand, and one has this problem that cannot connect with ADB tools. We had tired everything we can. After we did "FACTORY RESET", Temi is dead that cannot go to home page (lock on screen "waiting for docking" (initial procedure))

**Comment by ramisaban1** [comment]
Hello @uglyduck2019,

Please reach out to our support team via the mobile app or the website for further troubleshooting. This issue does not have anything to do with opening the ADB port.

**Comment by datablackhole** [comment]
> home
 Hey there uglyduck2019,

We have same exact problem now. We can't get past docking screen after factory reset. The support team said to tap on the top left corner of the display to get past this docking screen but now it just goes back to the same screen again and again.

Dear ramisaban1,
We have done exactly what you've showed in the video. No luck. But we are in contact with temi support team at moment. And no luck so far.  Is there a way to downgrade the software ?! because right now its nearly impossible to even that since we have no way to connect to temi i.e. via wifi. Is there a hidden usb port ?! .

**Comment by datablackhole** [comment]
> Hello @uglyduck2019,
> 
> Please reach out to our support team via the mobile app or the website for further troubleshooting. This issue does not have anything to do with opening the ADB port.


Dear ramisaban1,
This issue does **HAVE** a thing to do with opening the ADB port. Because this very ADB issue lead us to factory reset the device after having it upgraded to the latest software update.

**Comment by muhadnanafridi** [comment]
@ramisaban1 I tried to connect with 5 different networds  but its still not working .

**Comment by ramisaban1** [comment]
If anyone active on this issue is experiencing this and available to troubleshoot (with multiple networks, preferably a mobile hotspot), please reach out to live chat and ask for Rami. I should take over the chat and work with you from there.

**Comment by ramisaban1** [comment]
If anyone is still having this issue, please reach out to our live chat either on our website or directly from the temi mobile app on your smartphone and ask for Rami.

**Comment by datablackhole** [comment]
Temi team sent replacement robot because of this issue.

**Comment by ramisaban1** [comment]
Hello @datablackhole ,

Please reach out to live chat today and ask for Rami. I would love to speak to you regarding that issue.

**Comment by ramisaban1** [comment]
Otherwise, when would be a good time to speak?

**Comment by leslieam** [comment]
Please try with anther network. For example, your hotspot.

You network may have some policies which blocked the connection.

**Comment by nteku** [comment]
Hello! I am trying to connect my Temi Robot to a WPA-Enterprise network, but it is not letting me. Does anyone know how I can fix this?
