### ISSUE TITLE
disable moving status display during moving

### ISSUE THREAD

**Issue by william001415** [robotemi/sdk#410]
Can I disable the moving status display during go to location, not show “going”, “arrived” just display the customise screen on moving.
thanks

**Comment by zjn0505** [comment]
There is a setting of Full screen notification to control it

**Comment by fabiola29** [comment]
how you do it?

**Comment by zjn0505** [comment]
> how you do it?

In temi settings -> General Settings -> Fullscreen navigation notification. (Notifica di navigazione a schermo intero)

Or use this API, SETTINGS permission required.
https://github.com/robotemi/sdk/wiki/Utils#toggleNavigationBillboard
