### ISSUE TITLE
How to hide conversation layer

### ISSUE THREAD

**Issue by matteo-tm** [robotemi/sdk#423]
In the `speak`  API there is an option to hide conversation layer.
But in `askQuestion` and `startDefaultNlu` there seems to be no way to prevent the layer from showing. Is there a way to hide that?

**Comment by zjn0505** [comment]
startDefaultNlu is a way to trigger temi's default nlu, its reaction is not necessary to be a TTS.

**Comment by zjn0505** [comment]
In 133 version, askQuestion can take TtsRequest as parameter
https://github.com/robotemi/sdk/pull/454
