### ISSUE TITLE
Temi movement

### ISSUE THREAD

**Issue by hkryan** [robotemi/sdk#425]
Hi, I would like let Temi move forward one step and turn right without mapping in a progress of my app, but not success, which function I can use? if use robot.skidJoy(1f, 0.0f) in version 2 Temi tremor then stop, and don't want to display a "Remote" message on screen.

Thanks

**Comment by zjn0505** [comment]
The green label can be disabled from temi settings -> General settings -> Notifications.

Or use SDK method to disable it https://github.com/robotemi/sdk/wiki/Utils#setTopBadgeEnabled

**Comment by hkryan** [comment]
Thanks zjn0505
