### ISSUE TITLE
Speech, tablet follow bar and tap on screen stops the movement

### ISSUE THREAD

**Issue by lcarnevale** [robotemi/sdk#43]
Hello all,

While Temi drives to a desired location, the default behavior of the robot stops the movement when I tap the Tablet Follow Bar, the “Going to XYZ” screen or I say “hey temi”.

May I change this behavior to have a customized confirmation screen, such as the options to “Continue” and “Abort”?

Best,
Lorenzo.

**Comment by ramisaban1** [comment]
After hiding the "Going to the LOCATION_NAME" screen, you have the flexibility to customize the UI within your application and choose your desired action.

Regarding tapping the interaction bar, you can listen for any taps of that bar and act according to your liking by implementing the OnBeWithMeStatusChangedListener interface.
