### ISSUE TITLE
goTo() method parameters not matching documentation

### ISSUE THREAD

**Issue by BLG75** [robotemi/sdk#438]
Hello,

I am using the goTo() method to send temi to a location, and I would like him to drive backwards. In my IDE, goTo() only accepts the string parameter for a map location name. However in documentation I see goTo() defined with additional boolean parameters for Temi driving backwards, for instance. 

Why are these additional parameters not available in my project? Has this method been changed or replaced? Is there another method/ way to change the backwards and speed parameters outside of the goTo() method?
![goto method](https://github.com/robotemi/sdk/assets/41390315/325f7e7e-7158-4237-8820-b34ad51e617f)
![goto ide](https://github.com/robotemi/sdk/assets/41390315/e3514dd3-d594-4480-ba7b-f3fa0a6c77c1)

**Comment by OrenOneBi** [comment]
Hi,
It seems like you are using an older version of the robotemi sdk maven.
Make sure your version is as follows:
implementation 'com.robotemi:sdk:1.131.4'

**Comment by BLG75** [comment]
Thank you, that has resolved the issue
