### ISSUE TITLE
Button lock mode in Temi settings.

### ISSUE THREAD

**Issue by leeykdydrb** [robotemi/sdk#44]
I set the button lock mode in Temi settings.
Can I get rid of the messages, sounds, and vibrations when I press the follow action button and the volume touch button in this state?

**Comment by ramisaban1** [comment]
Currently, there is no way for you to get rid of the notification/sound/vibration that temi makes when pressing one of its buttons. However, we do have this request listed and our R&D team is reviewing this for possible implementation.

Thanks for the suggestion,
Rami
