### ISSUE TITLE
Speech to Text conversion

### ISSUE THREAD

**Issue by Ahad-Haque** [robotemi/sdk#445]
Hi, I'm trying to create an app in Temi where I want to show the words that user says. So, how can I convert speech into Text and show it?

**Comment by zjn0505** [comment]
You can use wakeup(), and get the text from onAsrResult()

**Comment by Ahad-Haque** [comment]
Can you please provide an example? @zjn0505 
here is what im trying to get, 

robot = Robot.getInstance()
private fun listen(){
        robot.wakeup()
        //String text = Please provide your implementation on getting text from onAsrResult()
        etSpeechToTextOutput.setText(text)
    }
    
    
Thank you very much!

**Comment by Ahad-Haque** [comment]
Nevermind I implemented the feature successfully. Thank you very much. @zjn0505
