### ISSUE TITLE
Automatic Text Recognition Problem

### ISSUE THREAD

**Issue by Ahad-Haque** [robotemi/sdk#447]
Hello, Is there any method in Temi, like I put some Text in a textbox and Temi replies to that Text just like ASR. Instead of listening the voice and reply it, I want to give text and Temi thinks & replies to that text.
Thank you.

**Comment by cyrus-rbc** [comment]
You may consider using the startDefaultNlu(text) function
https://github.com/robotemi/sdk/wiki/Speech#startdefaultnlu

**Comment by Ahad-Haque** [comment]
Yes was able to deploy it. Thank you.
