### ISSUE TITLE
Handle any mode in sdk

### ISSUE THREAD

**Issue by Lee827** [robotemi/sdk#45]
I want to turn on/off kiosk mode, hard button mode, privacy mode, auto return, standby mode in SDK to control something. Would you add this function to SDK? 

Thanks

**Comment by ramisaban1** [comment]
Hello @Lee827 ,

Thank you for reaching back out to us. This concern is noted and has been sent to our R&D team for further analysis and implementation.

Sorry I couldn't be of more help.

Best,
Rami
