### ISSUE TITLE
Control Temi from API

### ISSUE THREAD

**Issue by faysalbadaoui** [robotemi/sdk#455]
Is there any way to use api.robotemi.com to control my temi. So I can control It from external service?

**Comment by 25ahmed** [comment]
Can you please give us a quick summary on how you did that (controlling Temi from external device) ?

**Comment by faysalbadaoui** [comment]
There are multiple ways. You can use MQTT to send orders to an Andorid app running on you Temi, and then control it passing the location on the MQTT message. Or the same logic but using Push notifications instead of MQTT. But, I was interested on the API they use on Temi Center to do this, but I guess the API is not open to everyone.
