### ISSUE TITLE
node inactive on OnMovementStatusChangedListener turnBy

### ISSUE THREAD

**Issue by iJoris** [robotemi/sdk#457]
Hi,

At random times the OnMovementStatusChangedListener returns status STATUS_NODE_INACTIVE (node inactive) and then aborts.

Any reason why?

It only triggers when using robot.turnBy

**Comment by zjn0505** [comment]
I suppose this is a node issue in the algorithm core.

I heard from support team that the same issue has been reported there, I will close this issue and have the follow up on the technical support platform.
