### ISSUE TITLE
SRobot.askquestion("Ask question")  Display

### ISSUE THREAD

**Issue by Ghrissa** [robotemi/sdk#465]
SRobot.askquestion("Ask question") this method it will trigger ASR that I'm using for voice Recognition but the text is shown in the screen. I don't want any text to be shown. In addition, using space without anyting or using space. like this  SRobot.askquestion(" ")  it didn't make ASR work. Help me please

**Comment by zjn0505** [comment]
You can try the latest 133 version, there `askQuestion()` can take TtsRequest as parameter, and you can set it to not display text on screen.

https://github.com/robotemi/sdk/wiki/Speech#askQuestion

Your robot should run temi launcher version 17887 and SDK should be 1.133.0.

`askQuestion(" ")` will not speak so it cannot trigger follow up ASR. You can try `wakeup()` instead.
