### ISSUE TITLE
no response from asrlistener or nlplistener

### ISSUE THREAD

**Issue by dgolchin** [robotemi/sdk#49]
Hey guys,

I used both listeners from the sample code, nothing happened... 
everything else from sdk works fine, but only the these two listeners don't work. 
Nothing changed on the sample code. It's impossible to receive the user spoken words..
Any idea or solutions?

Best regards
david

**Comment by lcgao** [comment]
Hello David,

Please check follow things:
- Ensure the version of Launcher higher than 11969 (AsrListener).
- Ensure you have added the actions(home.welcome, home.dance..) as meta-data to AndroidManifest.xml (NlpListener).
- Ensure you have already added these two listeners to your Activity's onStart() method.
