### ISSUE TITLE
temi charging

### ISSUE THREAD

**Issue by Lee827** [robotemi/sdk#50]
What is the lowest battery energy temi will return back to the home base? Because I want to control return back home base in my apps. Can I close the auto-return back? (For charging)

**Comment by ramisaban1** [comment]
Hello,

Thank you for reaching out to temi's SDK team. You can easily call our Battery Listener to listen for any percent battery you want to return to the Home Base at and send the robot there.

Feel free to check out our documentation [here](https://github.com/robotemi/sdk/wiki).

Hint: Just add the Battery listener just like you would use any of temi's other listeners. 

Best,
Rami

**Comment by Lee827** [comment]
I know the Battery Listener. I am afraid your auto-return back function will run first. So I want to know the lowest battery energy and close the function. Let me easily to handle.
