### ISSUE TITLE
[Feature Request] Get Launcher Version

### ISSUE THREAD

**Issue by abduelhamit** [robotemi/sdk#51]
Many SDK features are dependent on the Launcher version.
But as far as I know, there is no way for an app to detect which version the robot has.

That is pretty unfortunate. Missing that information makes it impossible to use alternatives or inform the user about missing features.

Please implement a way to detect the Launcher version of the robot.

**Comment by ramisaban1** [comment]
Thank you for your request. I have noted it down for the R&D team to implement this within the SDK.

Stay Tuned!
