### ISSUE TITLE
Temi crashes in my application when i speak

### ISSUE THREAD

**Issue by muhadnanafridi** [robotemi/sdk#54]
Temi crashes in my application when i speak "hi temi " and say any thing which temi have no answer for it then my application crashed and i received that error . i also try this in kiosk mode but not working .
`02-18 10:52:03.668 10911-10989/com.roboteam.teamy.usa E/AudioRecord-JNI: Unable to retrieve AudioRecord object
02-18 10:52:04.328 227-227/? E/MediaPlayerFactory: 2019 03 30 -------- getPlayerType()44444444444444 call GET_PLAYER_TYPE_IMPL() !!!! 
02-18 10:52:04.345 227-22023/? E/OMXNodeInstance: setConfig(121:google.opus.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
02-18 10:52:07.697 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:07.733 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:10.646 10911-10911/com.roboteam.teamy.usa E/gedChannelOrphanWrapper: *~*~*~ Channel {0} was not shutdown properly!!! ~*~*~*
        Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
02-18 10:52:10.722 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:10.735 227-13707/? E/AudioHardwareTiny: adev_open_input_stream:channel is not support
02-18 10:52:10.752 227-22030/? E/AudioHardwareTiny: getInputRouteFromDevice:device:80000004
02-18 10:52:10.758 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:10.846 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:10.863 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:11.066 227-5435/? E/MediaPlayerFactory: 2019 03 30 -------- getPlayerType()44444444444444 call GET_PLAYER_TYPE_IMPL() !!!! 
02-18 10:52:11.088 227-22037/? E/OMXNodeInstance: setConfig(122:google.opus.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
02-18 10:52:14.603 227-633/? E/MediaPlayerFactory: 2019 03 30 -------- getPlayerType()44444444444444 call GET_PLAYER_TYPE_IMPL() !!!! 
02-18 10:52:14.621 227-22049/? E/OMXNodeInstance: setConfig(123:google.opus.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
02-18 10:52:16.940 227-227/? E/AudioHardwareTiny: adev_open_input_stream:channel is not support
02-18 10:52:16.954 227-22054/? E/AudioHardwareTiny: getInputRouteFromDevice:device:80000004
02-18 10:52:21.826 10911-11060/com.roboteam.teamy.usa E/AudioRecord-JNI: Unable to retrieve AudioRecord object
02-18 10:52:22.586 227-633/? E/MediaPlayerFactory: 2019 03 30 -------- getPlayerType()44444444444444 call GET_PLAYER_TYPE_IMPL() !!!! 
02-18 10:52:22.614 227-22065/? E/OMXNodeInstance: setConfig(124:google.opus.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
02-18 10:52:26.026 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:26.042 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:26.427 227-13707/? E/MediaPlayerFactory: 2019 03 30 -------- getPlayerType()---------------- 234 !!!! 
02-18 10:52:26.427 227-13707/? E/MediaPlayerFactory: filePath = /data/app/com.roboteam.teamy.usa-2/base.apk 
02-18 10:52:26.428 227-13707/? E/MediaPlayerFactory: 2019 03 30 -------- getPlayerType()---------------- return STAGEFRIGHT_PLAYER !!!! 
02-18 10:52:26.572 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:26.590 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:26.626 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:26.643 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:26.819 227-13707/? E/MediaPlayerFactory: 2019 03 30 -------- getPlayerType()44444444444444 call GET_PLAYER_TYPE_IMPL() !!!! 
02-18 10:52:26.853 227-22083/? E/OMXNodeInstance: setConfig(125:google.opus.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
02-18 10:52:27.439 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:27.444 227-633/? E/AudioHardwareTiny: adev_open_input_stream:channel is not support
02-18 10:52:27.461 227-22089/? E/AudioHardwareTiny: getInputRouteFromDevice:device:80000004
02-18 10:52:27.474 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:27.545 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:27.563 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:27.668 227-5719/? E/MediaPlayerFactory: 2019 03 30 -------- getPlayerType()44444444444444 call GET_PLAYER_TYPE_IMPL() !!!! 
02-18 10:52:27.702 227-22095/? E/OMXNodeInstance: setConfig(126:google.opus.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
02-18 10:52:29.438 555-591/system_process E/WindowManager: Unknown window type: 2999
02-18 10:52:35.011 10911-10989/com.roboteam.teamy.usa E/AudioRecord-JNI: Unable to retrieve AudioRecord object
02-18 10:52:35.927 227-633/? E/MediaPlayerFactory: 2019 03 30 -------- getPlayerType()44444444444444 call GET_PLAYER_TYPE_IMPL() !!!! 
02-18 10:52:35.959 227-22108/? E/OMXNodeInstance: setConfig(127:google.opus.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)`

**Comment by leslieam** [comment]
Is your application using microphone or audio recoder?

Can this be fixed by reboot the robot.
