### ISSUE TITLE
How to get the current location of Temi

### ISSUE THREAD

**Issue by pactera-yanglei** [robotemi/sdk#55]
How can we know where is Temi ，by coordinate axis or location?
Which api can support this function？

**Comment by yeh12141** [comment]
Currently , sdk doesn't provide such function as they're not sharing the map information

**Comment by lcgao** [comment]
Hello, we are working on this and get current position(x,y) feature will be available in the next one or two version.

**Comment by Robotrator** [comment]
Is it available now?

**Comment by lcgao** [comment]
https://github.com/robotemi/sdk/wiki/Locations#onCurrentPositionChangedListener
