### ISSUE TITLE
How to judge whether the user has finished a sentence by AsrListener

### ISSUE THREAD

**Issue by PacteraZhangTong** [robotemi/sdk#57]
When the user finishes a sentence, I want temi to do some operations, but I don't know how to judge whether the user has finished a sentence by AsrListener

**Comment by PacteraZhangTong** [comment]
OnAsrResult is called every time the user says a word, so how do I know that the user has finished a sentence?

**Comment by lcgao** [comment]
Hello, AsrListener can only receive the finished ASR sentence from user.
