### ISSUE TITLE
Auto-return back function

### ISSUE THREAD

**Issue by Lee827** [robotemi/sdk#58]
I know the Battery Listener. I am afraid your auto-return back function will run first. So I want to know the lowest battery energy and close the function. Let me easily to handle.
Thanks

_Originally posted by @Lee827 in https://github.com/robotemi/sdk/issues/50#issuecomment-584578273_

**Comment by yeh12141** [comment]
If I'm not wrong, Temi itself will alarm when the battery is at 15% and auto return when 10%.

**Comment by Lee827** [comment]
Alarm? How to tell me?

**Comment by yeh12141** [comment]
It's shows on the screen currently

**Comment by Lee827** [comment]
OK, Thank you. I will handle auto-return in my app.
