### ISSUE TITLE
如何配置本地nlp

### ISSUE THREAD

**Issue by wheatonchan** [robotemi/sdk#59]

**Comment by lcgao** [comment]
Settings(设置) -> temi Developers Tools(temi开发者选项) -> Local NLP(本地NLP) -> ADD NEW NLP(添加新的本地意图),
1. 然后依次填入‘语音文字内容’（语料，比如‘打开xxx’）和 ‘action名称’（意图，比如app.launch）。
2. 然后在AndroidManifest.xml中<application>标签下添加如下代码：
    ``` xml
    <meta-data
          android: name = "com.robotemi.sdk.metadata.ACTIONS"
          android: value = "app.launch" / >
    ```
    当你唤醒temi后对他刚刚填入的语料‘打开xxx‘，这时App就会跑起来并且把意图名称action‘app.launch’作为参数回传至onNlpCompleted(NlpResult nlpResult)回调方法中，当然前提是注册监听了NlpListener。

更多使用细节请参考GitHub Wiki：[https://github.com/robotemi/sdk/wiki/Home_chn](https://github.com/robotemi/sdk/wiki/Home_chn)
