### ISSUE TITLE
Can you control the timing of Temi's AI Assistant answer?

### ISSUE THREAD

**Issue by jams777** [robotemi/sdk#62]
For example, is it possible to:
1. Can I stop the robot's answer after the asr event?
2. Can the intent of all your statements be set to one action of local nlp?
3. Can I receive the default fallback action as a skill for all sentences?
4. Can the app respond to all intent skills provided by Temi's AI Assistant?

**Comment by leslieam** [comment]
In 119 version, you can replace the NLP with what ever you want.
https://github.com/robotemi/sdk/wiki/Speech#addAsrListener
