### ISSUE TITLE
Incorrect rotation with screen sharing

### ISSUE THREAD

**Issue by PureSecDE** [robotemi/sdk#65]
Hello, all,

we want to use the Android screen sharing function with Temi but unfortunately the screen is always rotated by 90 degrees. Is there a way to fix this problem? It seems so, so the tablet would think it's displayed in portrait mode.

To reproduce the problem easily you can also use the program [scrcpy](https://github.com/Genymobile/scrcpy), here we have the same failure and think that it is related.

Best,
PureSecDE

![temi_remote_screenshot](https://user-images.githubusercontent.com/62067311/76743725-5dc03900-6773-11ea-8999-cb7035f66fb3.jpeg)

**Comment by leslieam** [comment]
It will be fixed in a new firmware.

**Comment by icnocop** [comment]
Hi.

`adb shell wm size` returns `Physical size: 1200x1920` which is incorrect.

You can pass `--rotation 3` to `scrcpy.exe` and the screen will be rotated 90 degrees clockwise, but it will still be cut off.

See https://github.com/Genymobile/scrcpy#rotation

`The rotation can also be changed dynamically with Ctrl + ← (left) and Ctrl + → (right).`

I tried to call `adb shell wm size 1920x1200` and `adb shell wm overscan ...` but I wasn't able to fix the issue.

**Comment by leslieam** [comment]
Thanks for the info.
We've fixed the rotate issue in the new firmware and will release after we finish the test.

**Comment by hehao85** [comment]
How do I get the new firmware ?

**Comment by leslieam** [comment]
We'll release it when it is ready. You Should receive an update on your robot.

**Comment by dimitriosp** [comment]
Hello, reopening this one since it seems that it is still rotated and cut off. 
![image](https://user-images.githubusercontent.com/18033014/99951874-09983a80-2d7f-11eb-848a-b2ba962d90e7.png)
any update on this? 
best
