### ISSUE TITLE
Access Temi Device Id

### ISSUE THREAD

**Issue by collindutter** [robotemi/sdk#7]
Is there a way to get a unique identifier for the robot from the SDK? Best I've found is
`robot.getAdminInfo().getUserId()` but that doesn't work if the user has multiple Temis.

Thanks!

**Comment by NumanGillani-jackys** [comment]
Where can I find this ANDROID_ID  in Temi Settings?

In About Option of Temi Settings has Serial Number, and WiFi MAC Address that seems unique. I tried 7 methods to get Serial Numbers but didn't get Temi Serial Number, I got other numbers like c9d05xxx-2005-47bb-xxxx-e61f86xxxbef, 71TUSKxxxD. I kept xxxx text to hide original number.

**Comment by zjn0505** [comment]
We have provided this API.
[Robot.getSerialNumber](https://github.com/robotemi/sdk/wiki/Utils#getSerialNumber)
