### ISSUE TITLE
Knows if Temi can't move, or has fallen.

### ISSUE THREAD

**Issue by Beloin** [robotemi/sdk#73]
There's a way we can know by code if Temi can't move, or has fallen?
Since his upper part is larger than his body, there's as slightly chance it may fall; so knowing this should make it easier to prevent, or help Temi.

**Comment by leslieam** [comment]
We don't have an API to check temi fallen.

For go to status, you can refer [the document](https://github.com/robotemi/sdk/wiki/Locations#go-to-location-status-listener)
