### ISSUE TITLE
temi store download

### ISSUE THREAD

**Issue by iPre-Innovate** [robotemi/sdk#74]
Hi, we have uploaded our own application, AVATAR Robot for ZOOM in the temi store and has just been approved the other day. 

However, we see about 30 downloads on our screen, but cannot seem to access the app from the temi itself. 

Could you kindly let us know what the issue could be? Or is the temi marketplace still not public?

**Comment by ray-hrst** [comment]
@iPre-Innovate it's not very intuitive, but the marketplace is actually here: https://market.robotemi.com/. Maybe that will change in future revisions.

**Comment by leslieam** [comment]
This is our currently design. We may improve it in the future versions. 
Thank you for your advice.
