### ISSUE TITLE
how to update temi store app for bugfix

### ISSUE THREAD

**Issue by iPre-Innovate** [robotemi/sdk#77]
i want update temi store app that have aleady approved and enabled
i visit temi developer page and go in "Edit App Information" in my app
but the only apk upload button is disappeared

to update, should i submit more new app  ?

**Comment by leslieam** [comment]
I see that you've already submit one in the morning. Is it still relevant?
What is the website that you used to upload and trying to edit your app?

**Comment by iPre-Innovate** [comment]
yes, i have already submit one to edit Description  
i use following page
https://developer.robotemi.com/

**Comment by leslieam** [comment]
OK. Then please wait for our approval.
I'll close this issue.
Please open a new one if you still have issues.
