### ISSUE TITLE
Activity Stream Documentation

### ISSUE THREAD

**Issue by collindutter** [robotemi/sdk#8]
Are there any examples of how to use ActivityStreamMessage and ActivityStreamObject? I'm able to receive an ActivityStreamMessage after using the camera but I can't figure out how to get the picture from it.

Thanks!

**Comment by ramisaban1** [comment]
Hello Collin,

Sorry for the delayed response. If you wanted to upload to the Activities section on your mobile app, then you can use ActivityStreamObject. In the following example, a GIF of puppies in the public Download folder is being published to the ActivityStream. This is how you would use it:

```
activityStreamObject = ActivityStreamObject.builder()
                    .activityType(ActivityStreamObject.ActivityType.PHOTO)
                    .title("Puppies")
                    .media(MediaObject.create(MediaObject.MimeType.GIF, Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS + "/puppies.gif")))
                    .build();

           // Publishes to the activity stream 
            robot.shareActivityObject(activityStreamObject);
            robot.speak(TtsRequest.create("Uploading GIF", false));
```

**Comment by ramisaban1** [comment]
If you have any additional SDK questions or concerns feel free to reach out to developers@robotemi.com.

**Comment by collindutter** [comment]
Got it, I'll play around with this. Thank you!
