### ISSUE TITLE
when update new apk in temi developre site, uploading apk is stopped

### ISSUE THREAD

**Issue by iPre-Innovate** [robotemi/sdk#83]
As shown in the image below, the upload progress does not progress even after 1 hour or more.

<img width="1191" alt="スクリーンショット 2020-06-01 19 21 06" src="https://user-images.githubusercontent.com/27261960/83400276-859f6e80-a43d-11ea-9d82-4dfdb8bf7cd1.png">

**Comment by leslieam** [comment]
It's a bug of our platform. Not related to our SDK. 
We've reported to our internal team. And please report on Zendesk in temi app support
