### ISSUE TITLE
Can't use the SDK on smartphone or emulator with version 0.10.63.

### ISSUE THREAD

**Issue by Thiago-LM** [robotemi/sdk#84]
Hi, I'm part of a team and we are working on a temi application. Due to quarentine and only having one temi to work with, some of us have to use our smartphones and emulators to develop the app.

And after the upgrade to '0.10.63' the app won't launch on a android smartphone or emulator, we are forced to use '0.10.53'.

Simply creating a new app on Android Studio and importing the sdk will cause the app to not open.

1. Create a Basic Activity app
![Screenshot_20200601_235911](https://user-images.githubusercontent.com/37124257/83476088-4c87ee00-a47f-11ea-98fe-1967c61187f8.png)

2. Don't change anything
![Screenshot_20200602_000200](https://user-images.githubusercontent.com/37124257/83476146-6b868000-a47f-11ea-90eb-9294789d3390.png)

3. Import the SDK
![Screenshot_20200602_002253](https://user-images.githubusercontent.com/37124257/83476475-6544d380-a480-11ea-8e62-ac799b199927.png)

I've even tried the '0.10.65', which Android Studio suggests, but no luck. All versions work on temi, the problem only occurs on an smartphone or emulator.

**Comment by lcgao** [comment]
Hello,
In later versions of v0.10.6, if the App fails to connect to temi through the SDK, the SDK will execute the action to kill the current process.
