### ISSUE TITLE
Best practice for reading Barcode from Temi

### ISSUE THREAD

**Issue by cyrsis** [robotemi/sdk#87]
We sort of have couple project deal with barcode scanning,

I have tough time work out the range with the Temi Scan Barcode, not so easy to detech actual barcode, is there any good example to work with?

The barcode can be 2D and 1D..

Thanks

**Comment by leslieam** [comment]
There're many service available. Please search it on github or other search engine.
I'm sorry I can not disclose this to you.

**Comment by dimitriosp** [comment]
@cyrsis  
you could look into: 
https://developers.google.com/ml-kit/vision/barcode-scanning/android
