### ISSUE TITLE
Running TEMI in offline

### ISSUE THREAD

**Issue by jwson1** [robotemi/sdk#88]
I installed SDK sample, and tried to run in offline (without WIFI). But TEMI gives an error message "This feature is not available while TEMI is offline'.
It is bad news for me as I am targeting to developing new TEMI app for a secure area where WIFI is not allowed.
If I make my new custom app, should it run on WIFI enviroment? I have no plan to use an internet connection in my custom app.

**Comment by lcgao** [comment]
Hello,
Please add following code to `<application>` in AndroidMainfest.xml:
``` xml
<meta-data
    android:name="@string/metadata_open_without_internet"
    android:value="TRUE" />
```
