### ISSUE TITLE
Add dynamic location points to the map

### ISSUE THREAD

**Issue by dimitriosp** [robotemi/sdk#92]
Hello,
one of our customers asked if its possible to dynamically add location points to the map, without having temi physically drive there. 
This would need to get the map and be able to add new locations and update the map on the robot.

best 
Dimitrios

**Comment by lcgao** [comment]
Hello, We are working on this, but this is only for the Web platform not for SDK.

**Comment by dimitriosp** [comment]
So the customer app could add dynamic locations to the cloud, but how does the robot receive the updated map then?

**Comment by lcgao** [comment]
Customer's App couldn't add dynamic locations to the cloud directly. By the way I want to the question you asked that did you just want to add a location(location name) in your own App? if so, you could use `Robot.getInstance().saveLocation(locationName)` to implement that and no need to get the map.

**Comment by dimitriosp** [comment]
Hello, reopening this, sorry for the delay.

The use case would be:
- map of the environment is available on the robot and cloud
- a new dynamic previously unknown location is added to the cloud map
- the map is pushed to temi and loaded as new map
- now the robot navigates to the new location

Is this possible?
best Dimitrios
