### ISSUE TITLE
possible to pause robot when asked to goto() ?

### ISSUE THREAD

**Issue by kerliang0801** [robotemi/sdk#97]
Hello! I was just wondering if it was possible to pause temi when it is on route to a location using goto(). maybe could we execute stopmovement() after a goto() call?

**Comment by lcgao** [comment]
Hello, you are right. [`Robot.getInstance().stopMovement()`](https://github.com/robotemi/sdk/wiki/Movement#stop-movement) is a good way to stop the navigation or other movement.
