### ISSUE TITLE
Is it possible to directly say "Hello" to temi?

### ISSUE THREAD

**Issue by MeiShin00** [robotemi/sdk#99]
I have a question about onAsrResult function. For example, before you say "Hello" to temi you need to say "Hey, temi" before that. Is it possible to directly say "Hello" to temi without the "Hey, temi"?

**Comment by lcgao** [comment]
Please use [`Robot.getInstance().wakeup();`](https://github.com/robotemi/sdk/wiki/Speech#wakeup) instead.
